#ifndef GUI_IDS_H
#define GUI_IDS_H

#include <wx/defs.h>

enum {
    ID_FIRST = wxID_HIGHEST,

    // File
    ID_FILE_NEW_PROJECT,
    ID_FILE_LOAD,
    ID_FILE_BROWSE_LOAD,
    ID_FILE_SAVE_BIN,

    // Simulation
    ID_SIM_RUN,
    ID_SIM_PAUSE,
    ID_SIM_STEP_INTO,
    ID_SIM_STEP_OVER,
    ID_SIM_RESET,
    ID_SIM_CLEAR_CYCLES,
    ID_SIM_TOGGLE_BREAKPOINT,
    ID_SIM_STEP_BACK,
    ID_SIM_STEP_FORWARD,
    ID_SIM_REVERSE_CONTINUE,
    ID_SIM_THROTTLE_SPEED,

    // Machine
    ID_MACH_ADD_DEVICE,
    ID_MACH_PROC_6502,
    ID_MACH_PROC_6502_UNDOC,
    ID_MACH_PROC_65C02,
    ID_MACH_PROC_65CE02,
    ID_MACH_PROC_45GS02,
    ID_MACH_TYPE_RAW,
    ID_MACH_TYPE_C64,
    ID_MACH_TYPE_C128,
    ID_MACH_TYPE_MEGA65,
    ID_MACH_TYPE_X16,

    // View
    ID_VIEW_GO_TO_ADDRESS,
    ID_VIEW_PANE_REGISTERS,
    ID_VIEW_PANE_DISASSEMBLY,
    ID_VIEW_PANE_MEMORY_1,
    ID_VIEW_PANE_MEMORY_2,
    ID_VIEW_PANE_MEMORY_3,
    ID_VIEW_PANE_MEMORY_4,
    ID_VIEW_PANE_CONSOLE,
    ID_VIEW_PANE_BREAKPOINTS,
    ID_VIEW_PANE_TRACE,
    ID_VIEW_PANE_STACK,
    ID_VIEW_PANE_WATCHES,
    ID_VIEW_PANE_SNAP_DIFF,
    ID_VIEW_PANE_IREF,
    ID_VIEW_PANE_SYMBOLS,
    ID_VIEW_PANE_SOURCE,
    ID_VIEW_PANE_PROFILER,
    ID_VIEW_PANE_TEST_RUNNER,
    ID_VIEW_PANE_DEVICES,
    ID_VIEW_PANE_PATTERNS,
    ID_VIEW_PANE_VIC_SCREEN,
    ID_VIEW_PANE_VIC_CHARS,
    ID_VIEW_PANE_VIC_SPRITES,
    ID_VIEW_PANE_VIC_REGS,
    ID_VIEW_PANE_SID_DEBUGGER,
    ID_VIEW_PANE_AUDIO_MIXER,

    ID_VIEW_FONT_SIZE_10,
    ID_VIEW_FONT_SIZE_11,
    ID_VIEW_FONT_SIZE_12,
    ID_VIEW_FONT_SIZE_13,
    ID_VIEW_FONT_SIZE_14,
    ID_VIEW_FONT_SIZE_15,
    ID_VIEW_FONT_SIZE_16,
    ID_VIEW_FONT_SIZE_18,
    ID_VIEW_FONT_SIZE_20,
    ID_VIEW_FONT_SIZE_24,

    ID_VIEW_THEME_AUTO,
    ID_VIEW_THEME_DARK,
    ID_VIEW_THEME_LIGHT,

    ID_VIEW_LAYOUT_SAVE,
    ID_VIEW_LAYOUT_RESET,

    ID_IREF_FIND_IN_DISASM,

    // Window
    ID_WINDOW_ARRANGE,

    ID_TOOLBAR_PROC_COMBO,
    ID_TOOLBAR_MACH_COMBO,

    ID_LAST
};

#endif // GUI_IDS_H
