; Test all instructions for 45gs02
; Generated by generate_opcode_tests.py
  .processor 45gs02
  .org $1000

  LDA      #$12
  LDA      $1234
  LDA      $1234,X
  LDA      $1234,Y
  LDA      $12
  LDA      $12,X
  ASW      $1234
  ROW      $1234
  DEW      $12
  INW      $12
  PHW      #$1234
  PHW      $1234
  PHZ     
  PLZ     
  LDZ      $1234,X
  TSY     
  TYS     
  TAZ     
  TZA     
  CLE     
  SEE     
  NEG     
  TAB     
  TBA     
  RTN      #$12
  BSR      *+4
  LBSR     *+4
  ASR     
  ASR      $12
  ASR      $12,X
  MAP     
  LDA      ($12,X)
  LDA      ($12),Y
  LDZ      #$12
  LDZ      $1234
  LDX      #$12
  LDX      $1234
  LDX      $1234,Y
  LDX      $12
  LDX      $12,Y
  LDY      #$12
  LDY      $1234
  LDY      $1234,X
  LDY      $12
  LDY      $12,X
  STA      $1234
  STA      $1234,X
  STA      $1234,Y
  STA      $12
  STA      $12,X
  STA      ($12,X)
  STA      ($12),Y
  STZ      $1234
  STZ      $12
  STX      $1234
  STX      $12
  STX      $12,Y
  STX      $1234,Y
  STY      $1234
  STY      $12
  STY      $12,X
  STY      $1234,X
  ADC      #$12
  ADC      $1234
  ADC      $1234,X
  ADC      $1234,Y
  ADC      $12
  ADC      $12,X
  ADC      ($12,X)
  ADC      ($12),Y
  SBC      #$12
  SBC      $1234
  SBC      $12
  SBC      $12,X
  SBC      ($12,X)
  SBC      ($12),Y
  SBC      $1234,Y
  SBC      $1234,X
  LDA      ($12),Z
  LDA      ($12,SP),Y
  STA      ($12),Z
  STA      ($12,SP),Y
  ADC      ($12),Z
  SBC      ($12),Z
  CMP      ($12),Z
  ORA      ($12),Z
  AND      ($12),Z
  EOR      ($12),Z
  LDA      [$12],Z
  STA      [$12],Z
  ADC      [$12],Z
  SBC      [$12],Z
  CMP      [$12],Z
  ORA      [$12],Z
  AND      [$12],Z
  EOR      [$12],Z
  CMP      #$12
  CMP      $1234
  CMP      $12
  CMP      $12,X
  CMP      ($12,X)
  CMP      ($12),Y
  CMP      $1234,Y
  CMP      $1234,X
  CPZ      #$12
  CPZ      $1234
  CPZ      $12
  CPX      #$12
  CPX      $12
  CPX      $1234
  CPY      #$12
  CPY      $12
  CPY      $1234
  INC      $1234
  INC      $12
  INC      $12,X
  INC      $1234,X
  INA     
  INX     
  INY     
  INZ     
  DEC      $1234
  DEC      $12
  DEC      $12,X
  DEC      $1234,X
  DEA     
  DEX     
  DEY     
  DEZ     
  ASL      $1234
  ASL     
  ASL      $12
  ASL      $12,X
  ASL      $1234,X
  LSR      $1234
  LSR     
  LSR      $12
  LSR      $12,X
  LSR      $1234,X
  ROL      $1234
  ROL     
  ROL      $12
  ROL      $12,X
  ROL      $1234,X
  ROR      $1234
  ROR     
  ROR      $12
  ROR      $12,X
  ROR      $1234,X
  AND      #$12
  AND      $1234
  AND      $12
  AND      $12,X
  AND      ($12,X)
  AND      ($12),Y
  AND      $1234,Y
  AND      $1234,X
  EOR      #$12
  EOR      $1234
  EOR      $12
  EOR      $12,X
  EOR      ($12,X)
  EOR      ($12),Y
  EOR      $1234,Y
  EOR      $1234,X
  ORA      #$12
  ORA      $1234
  ORA      $12
  ORA      $12,X
  ORA      ($12,X)
  ORA      ($12),Y
  ORA      $1234,Y
  ORA      $1234,X
  BIT      $12
  BIT      $1234
  BIT      #$12
  BIT      $12,X
  BIT      $1234,X
  TRB      $12
  TRB      $1234
  TSB      $12
  TSB      $1234
  RMB0     $12
  RMB1     $12
  RMB2     $12
  RMB3     $12
  RMB4     $12
  RMB5     $12
  RMB6     $12
  RMB7     $12
  SMB0     $12
  SMB1     $12
  SMB2     $12
  SMB3     $12
  SMB4     $12
  SMB5     $12
  SMB6     $12
  SMB7     $12
  BBR0     $12
  BBR1     $12
  BBR2     $12
  BBR3     $12
  BBR4     $12
  BBR5     $12
  BBR6     $12
  BBR7     $12
  BBS0     $12
  BBS1     $12
  BBS2     $12
  BBS3     $12
  BBS4     $12
  BBS5     $12
  BBS6     $12
  BBS7     $12
  STZ      $1234
  STZ      $1234,X
  STZ      $12
  STZ      $12,X
  BRA      *+3
  BRA      *+4
  BRL      *+4
  LBRA     *+4
  JMP      $1234
  JMP      ($1234)
  JMP      ($12,X)
  JSR      $1234
  JSR      ($1234)
  JSR      ($1234,X)
  RTS     
  BCC      *+3
  BCC      *+4
  LBCC     *+4
  BCS      *+3
  BCS      *+4
  LBCS     *+4
  BEQ      *+3
  BEQ      *+4
  LBEQ     *+4
  BNE      *+3
  BNE      *+4
  LBNE     *+4
  BMI      *+3
  BMI      *+4
  LBMI     *+4
  BPL      *+3
  BPL      *+4
  LBPL     *+4
  BVS      *+3
  BVS      *+4
  LBVS     *+4
  BVC      *+3
  BVC      *+4
  LBVC     *+4
  CLC     
  SEC     
  CLD     
  SED     
  CLI     
  SEI     
  CLV     
  TAX     
  TXA     
  TAY     
  TYA     
  TSX     
  TXS     
  PHA     
  PLA     
  PHX     
  PLX     
  PHY     
  PLY     
  PHP     
  PLP     
  BRK     
  RTI     
  EOM     
  LDQ      $12
  LDQ      $1234
  LDQ      ($12),Z
  STQ      $12
  STQ      $1234
  STQ      ($12),Z
  LDQ      [$12],Z
  STQ      [$12],Z
  ADCQ     $12
  ADCQ     $1234
  SBCQ     $12
  SBCQ     $1234
  CPQ      $12
  CPQ      $1234
  EORQ     $12
  EORQ     $1234
  ANDQ     $12
  ANDQ     $1234
  BITQ     $12
  BITQ     $1234
  ORQ      $12
  ORQ      $1234
  ASLQ    
  ASLQ     $12
  ASLQ     $12,X
  ASLQ     $1234
  ASLQ     $1234,X
  ASRQ    
  ASRQ     $12
  ASRQ     $12,X
  LSRQ    
  LSRQ     $12
  LSRQ     $12,X
  LSRQ     $1234
  LSRQ     $1234,X
  ROLQ    
  ROLQ     $12
  ROLQ     $12,X
  ROLQ     $1234
  ROLQ     $1234,X
  RORQ    
  RORQ     $12
  RORQ     $12,X
  RORQ     $1234
  RORQ     $1234,X
  INQ     
  INQ      $12
  INQ      $12,X
  INQ      $1234
  INQ      $1234,X
  DEQ     
  DEQ      $12
  DEQ      $12,X
  DEQ      $1234
  DEQ      $1234,X
  ADCQ     ($12),Z
  ADCQ     [$12],Z
  SBCQ     ($12),Z
  SBCQ     [$12],Z
  CPQ      ($12),Z
  CPQ      [$12],Z
  ANDQ     ($12),Z
  ANDQ     [$12],Z
  EORQ     ($12),Z
  EORQ     [$12],Z
  ORQ      ($12),Z
  ORQ      [$12],Z

  .byte 0 ; BRK
