; Test all instructions for 6502
; Generated by generate_opcode_tests.py
  .processor 6502
  .org $1000

  LDA      #$12
  LDA      $1234
  LDA      $1234,X
  LDA      $1234,Y
  LDA      $12
  LDA      $12,X
  LDA      ($12,X)
  LDA      ($12),Y
  LDX      #$12
  LDX      $1234
  LDX      $1234,Y
  LDX      $12
  LDX      $12,Y
  LDY      #$12
  LDY      $1234
  LDY      $1234,X
  LDY      $12
  LDY      $12,X
  STA      $1234
  STA      $1234,X
  STA      $1234,Y
  STA      $12
  STA      $12,X
  STA      ($12,X)
  STA      ($12),Y
  STX      $1234
  STX      $12
  STX      $12,Y
  STY      $1234
  STY      $12
  STY      $12,X
  ADC      #$12
  ADC      $1234
  ADC      $1234,X
  ADC      $1234,Y
  ADC      $12
  ADC      $12,X
  ADC      ($12,X)
  ADC      ($12),Y
  SBC      #$12
  SBC      $1234
  SBC      $12
  SBC      $12,X
  SBC      $1234,X
  SBC      $1234,Y
  SBC      ($12,X)
  SBC      ($12),Y
  CMP      #$12
  CMP      $1234
  CMP      $12
  CMP      $12,X
  CMP      $1234,X
  CMP      $1234,Y
  CMP      ($12,X)
  CMP      ($12),Y
  CPX      #$12
  CPX      $12
  CPX      $1234
  CPY      #$12
  CPY      $12
  CPY      $1234
  INC      $1234
  INC      $12
  INC      $12,X
  INC      $1234,X
  INA     
  INX     
  INY     
  DEC      $1234
  DEC      $12
  DEC      $12,X
  DEC      $1234,X
  DEA     
  DEX     
  DEY     
  ASL      $1234
  ASL      $12
  ASL      $12,X
  ASL      $1234,X
  ASL     
  LSR      $1234
  LSR      $12
  LSR      $12,X
  LSR      $1234,X
  LSR     
  ROL      $1234
  ROL      $12
  ROL      $12,X
  ROL      $1234,X
  ROL     
  ROR      $1234
  ROR      $12
  ROR      $12,X
  ROR      $1234,X
  ROR     
  AND      #$12
  AND      $1234
  AND      $12
  AND      $12,X
  AND      $1234,X
  AND      $1234,Y
  AND      ($12,X)
  AND      ($12),Y
  EOR      #$12
  EOR      $1234
  EOR      $12
  EOR      $12,X
  EOR      $1234,X
  EOR      $1234,Y
  EOR      ($12,X)
  EOR      ($12),Y
  ORA      #$12
  ORA      $1234
  ORA      $12
  ORA      $12,X
  ORA      $1234,X
  ORA      $1234,Y
  ORA      ($12,X)
  ORA      ($12),Y
  BIT      $12
  BIT      $1234
  JMP      $1234
  JMP      ($1234)
  JSR      $1234
  RTS     
  BRA      *+3
  BCC      *+3
  BCS      *+3
  BEQ      *+3
  BNE      *+3
  BMI      *+3
  BPL      *+3
  BVS      *+3
  BVC      *+3
  CLC     
  SEC     
  CLD     
  SED     
  CLI     
  SEI     
  CLV     
  TAX     
  TXA     
  TAY     
  TYA     
  TSX     
  TXS     
  PHA     
  PLA     
  PHP     
  PLP     
  BRK     
  RTI     
  NOP     

  .byte 0 ; BRK
