; Test all instructions for 6502_undoc
; Generated by generate_opcode_tests.py
  .processor 6502 undoc
  .org $1000

  LDA      #$12
  LDA      $1234
  LDA      $1234,X
  LDA      $1234,Y
  LDA      $12
  LDA      $12,X
  LDA      ($12,X)
  LDA      ($12),Y
  LDX      #$12
  LDX      $1234
  LDX      $1234,Y
  LDX      $12
  LDX      $12,Y
  LDY      #$12
  LDY      $1234
  LDY      $1234,X
  LDY      $12
  LDY      $12,X
  STA      $1234
  STA      $1234,X
  STA      $1234,Y
  STA      $12
  STA      $12,X
  STA      ($12,X)
  STA      ($12),Y
  STX      $1234
  STX      $12
  STX      $12,Y
  STY      $1234
  STY      $12
  STY      $12,X
  ADC      #$12
  ADC      $1234
  ADC      $1234,X
  ADC      $1234,Y
  ADC      $12
  ADC      $12,X
  ADC      ($12,X)
  ADC      ($12),Y
  SBC      #$12
  SBC      $1234
  CMP      #$12
  CMP      $1234
  CPX      #$12
  CPY      #$12
  INC      $1234
  INA     
  INX     
  INY     
  DEC      $1234
  DEA     
  DEX     
  DEY     
  ASL      $1234
  ASL     
  LSR      $1234
  LSR     
  ROL      $1234
  ROL     
  ROR      $1234
  ROR     
  AND      #$12
  AND      $1234
  EOR      #$12
  EOR      $1234
  ORA      #$12
  ORA      $1234
  BIT      $1234
  JMP      $1234
  JSR      $1234
  RTS     
  BRA      *+3
  BCC      *+3
  BCS      *+3
  BEQ      *+3
  BNE      *+3
  BMI      *+3
  BPL      *+3
  BVS      *+3
  BVC      *+3
  CLC     
  SEC     
  CLD     
  SED     
  CLI     
  SEI     
  CLV     
  TAX     
  TXA     
  TAY     
  TYA     
  TSX     
  TXS     
  PHA     
  PLA     
  PHP     
  PLP     
  BRK     
  RTI     
  NOP     
  LAX      $1234
  LAX      $1234,Y
  LAX      $12
  LAX      $12,Y
  LAX      ($12),Y
  SAX      $1234
  SAX      $12
  SAX      $12,Y
  SAX      ($12,X)
  DCM      $1234
  DCM      $12
  INS      $1234
  INS      $12
  ASR      #$12
  ARR      #$12
  ALR      #$12
  ANC      #$12
  SLO      $1234
  SLO      $1234,X
  SLO      $1234,Y
  SLO      $12
  SLO      $12,X
  SLO      ($12,X)
  SLO      ($12),Y
  SRE      $1234
  SRE      $12
  RLA      $1234
  RLA      $12
  RRA      $1234
  RRA      $12

  .byte 0 ; BRK
