; Test all instructions for 65c02
; Generated by generate_opcode_tests.py
  .processor 65c02
  .org $1000

  LDA      #$12
  LDA      $1234
  LDA      $1234,X
  LDA      $1234,Y
  LDA      $12
  LDA      $12,X
  LDA      ($12,X)
  LDA      ($12),Y
  LDX      #$12
  LDX      $1234
  LDX      $1234,Y
  LDX      $12
  LDX      $12,Y
  LDY      #$12
  LDY      $1234
  LDY      $1234,X
  LDY      $12
  LDY      $12,X
  STA      $1234
  STA      $1234,X
  STA      $1234,Y
  STA      $12
  STA      $12,X
  STA      ($12,X)
  STA      ($12),Y
  STX      $1234
  STX      $12
  STX      $12,Y
  STY      $1234
  STY      $12
  STY      $12,X
  ADC      #$12
  ADC      $1234
  ADC      $1234,X
  ADC      $1234,Y
  ADC      $12
  ADC      $12,X
  ADC      ($12,X)
  ADC      ($12),Y
  SBC      #$12
  SBC      $1234
  CMP      #$12
  CMP      $1234
  CPX      #$12
  CPY      #$12
  INC      $1234
  INA     
  INX     
  INY     
  DEC      $1234
  DEA     
  DEX     
  DEY     
  ASL      $1234
  ASL     
  LSR      $1234
  LSR     
  ROL      $1234
  ROL     
  ROR      $1234
  ROR     
  AND      #$12
  AND      $1234
  EOR      #$12
  EOR      $1234
  ORA      #$12
  ORA      $1234
  BIT      $12
  BIT      $1234
  BIT      #$12
  BIT      $12,X
  BIT      $1234,X
  TRB      $12
  TRB      $1234
  TSB      $12
  TSB      $1234
  RMB0     $12
  RMB1     $12
  RMB2     $12
  RMB3     $12
  RMB4     $12
  RMB5     $12
  RMB6     $12
  RMB7     $12
  SMB0     $12
  SMB1     $12
  SMB2     $12
  SMB3     $12
  SMB4     $12
  SMB5     $12
  SMB6     $12
  SMB7     $12
  BBR0     $12
  BBR1     $12
  BBR2     $12
  BBR3     $12
  BBR4     $12
  BBR5     $12
  BBR6     $12
  BBR7     $12
  BBS0     $12
  BBS1     $12
  BBS2     $12
  BBS3     $12
  BBS4     $12
  BBS5     $12
  BBS6     $12
  BBS7     $12
  STZ      $1234
  STZ      $1234,X
  STZ      $12
  STZ      $12,X
  BRA      *+3
  BRL      *+3
  JMP      $1234
  JMP      ($1234)
  JMP      ($12,X)
  JSR      $1234
  RTS     
  BCC      *+3
  BCS      *+3
  BEQ      *+3
  BNE      *+3
  BMI      *+3
  BPL      *+3
  BVS      *+3
  BVC      *+3
  CLC     
  SEC     
  CLD     
  SED     
  CLI     
  SEI     
  CLV     
  TAX     
  TXA     
  TAY     
  TYA     
  TSX     
  TXS     
  PHA     
  PLA     
  PHP     
  PLP     
  BRK     
  RTI     
  NOP     

  .byte 0 ; BRK
