 // Test all instructions for 65c02

 // Generated by generate_opcode_tests.py

    .cpu _65ce02
    * = $1000

    lda #$12
    lda $1234
    lda $1234,x
    lda $1234,y
    lda $12
    lda $12,x
    lda ($12,x)
    lda ($12),y
    ldx #$12
    ldx $1234
    ldx $1234,y
    ldx $12
    ldx $12,y
    ldy #$12
    ldy $1234
    ldy $1234,x
    ldy $12
    ldy $12,x
    sta $1234
    sta $1234,x
    sta $1234,y
    sta $12
    sta $12,x
    sta ($12,x)
    sta ($12),y
    stx $1234
    stx $12
    stx $12,y
    sty $1234
    sty $12
    sty $12,x
    adc #$12
    adc $1234
    adc $1234,x
    adc $1234,y
    adc $12
    adc $12,x
    adc ($12,x)
    adc ($12),y
    sbc #$12
    sbc $1234
    cmp #$12
    cmp $1234
    cpx #$12
    cpy #$12
    inc $1234
    inc
    inx
    iny
    dec $1234
    dec
    dex
    dey
    asl $1234
    asl
    lsr $1234
    lsr
    rol $1234
    rol
    ror $1234
    ror
    and #$12
    and $1234
    eor #$12
    eor $1234
    ora #$12
    ora $1234
    bit $12
    bit $1234
    bit #$12
    bit $12,x
    bit $1234,x
    trb $12
    trb $1234
    tsb $12
    tsb $1234
    rmb0 $12
    rmb1 $12
    rmb2 $12
    rmb3 $12
    rmb4 $12
    rmb5 $12
    rmb6 $12
    rmb7 $12
    smb0 $12
    smb1 $12
    smb2 $12
    smb3 $12
    smb4 $12
    smb5 $12
    smb6 $12
    smb7 $12
    bbr0 $12, *+3
    bbr1 $12, *+3
    bbr2 $12, *+3
    bbr3 $12, *+3
    bbr4 $12, *+3
    bbr5 $12, *+3
    bbr6 $12, *+3
    bbr7 $12, *+3
    bbs0 $12, *+3
    bbs1 $12, *+3
    bbs2 $12, *+3
    bbs3 $12, *+3
    bbs4 $12, *+3
    bbs5 $12, *+3
    bbs6 $12, *+3
    bbs7 $12, *+3
    stz $1234
    stz $1234,x
    stz $12
    stz $12,x
    bra *+3
    lbra *+3
    jmp $1234
    jmp ($1234)
    jmp ($12,x)
    jsr $1234
    rts
    bcc *+3
    bcs *+3
    beq *+3
    bne *+3
    bmi *+3
    bpl *+3
    bvs *+3
    bvc *+3
    clc
    sec
    cld
    sed
    cli
    sei
    clv
    tax
    txa
    tay
    tya
    tsx
    txs
    pha
    pla
    php
    plp
    brk
    rti
    nop

    .byte 0 // BRK

