#include "patterns.h"
#include <string.h>

/* =========================================================================
 * add16
 * ========================================================================= */
static const char s_add16[] =
"; add16 — 16-bit addition\n"
";\n"
"; Adds a 16-bit source value to a 16-bit destination, both in zero page.\n"
";\n"
"; PARAMS — change these equates to suit your layout:\n"
";   SRC_LO  = source  low  byte address\n"
";   SRC_HI  = source  high byte address  (SRC_LO + 1)\n"
";   DST_LO  = destination low  byte address\n"
";   DST_HI  = destination high byte address  (DST_LO + 1)\n"
";\n"
"; Result : [DST_HI:DST_LO] += [SRC_HI:SRC_LO]\n"
"; Clobbers: A, N, Z, C, V\n"
"; Cycles  : 14\n"
";\n"
"SRC_LO  = $10\n"
"SRC_HI  = $11\n"
"DST_LO  = $12\n"
"DST_HI  = $13\n"
"\n"
"add16:\n"
"    CLC\n"
"    LDA DST_LO\n"
"    ADC SRC_LO\n"
"    STA DST_LO\n"
"    LDA DST_HI\n"
"    ADC SRC_HI\n"
"    STA DST_HI\n"
"    RTS\n";

/* =========================================================================
 * sub16
 * ========================================================================= */
static const char s_sub16[] =
"; sub16 — 16-bit subtraction\n"
";\n"
"; Subtracts a 16-bit source from a 16-bit destination, both in zero page.\n"
";\n"
"; PARAMS:\n"
";   SRC_LO  = subtrahend low  byte address\n"
";   SRC_HI  = subtrahend high byte address\n"
";   DST_LO  = minuend / result low  byte address\n"
";   DST_HI  = minuend / result high byte address\n"
";\n"
"; Result : [DST_HI:DST_LO] -= [SRC_HI:SRC_LO]\n"
"; Clobbers: A, N, Z, C, V\n"
"; Cycles  : 14\n"
";\n"
"SRC_LO  = $10\n"
"SRC_HI  = $11\n"
"DST_LO  = $12\n"
"DST_HI  = $13\n"
"\n"
"sub16:\n"
"    SEC\n"
"    LDA DST_LO\n"
"    SBC SRC_LO\n"
"    STA DST_LO\n"
"    LDA DST_HI\n"
"    SBC SRC_HI\n"
"    STA DST_HI\n"
"    RTS\n";

/* =========================================================================
 * mul8  — software 8×8 = 16-bit (shift-and-add), all 6502 variants
 * ========================================================================= */
static const char s_mul8[] =
"; mul8 — unsigned 8x8 = 16-bit multiply (software, all 6502 variants)\n"
";\n"
"; Standard shift-and-add algorithm (8 iterations).\n"
";\n"
"; PARAMS:\n"
";   FACTOR_A  = $10   ; 8-bit multiplicand (preserved)\n"
";   FACTOR_B  = $11   ; 8-bit multiplier   (destroyed — shift register)\n"
";   RESULT_LO = $12   ; product low  byte  (out)\n"
";   RESULT_HI = $13   ; product high byte  (out)\n"
";   TMP_HI    = $14   ; high byte of shifted FACTOR_A (internal)\n"
";\n"
"; Result : [RESULT_HI:RESULT_LO] = FACTOR_A * FACTOR_B  (0..65025)\n"
"; Clobbers: A, X, FACTOR_B, TMP_HI, N, Z, C\n"
"; Cycles  : ~153 worst-case\n"
";\n"
"FACTOR_A  = $10\n"
"FACTOR_B  = $11\n"
"RESULT_LO = $12\n"
"RESULT_HI = $13\n"
"TMP_HI    = $14\n"
"\n"
"mul8:\n"
"    LDA #0\n"
"    STA RESULT_LO\n"
"    STA RESULT_HI\n"
"    STA TMP_HI\n"
"    LDX #8              ; 8 bit-iterations\n"
".mul8_loop:\n"
"    LSR FACTOR_B        ; shift multiplier right; bit 0 -> carry\n"
"    BCC .mul8_skip      ; bit was 0: skip add\n"
"    CLC\n"
"    LDA RESULT_LO\n"
"    ADC FACTOR_A\n"
"    STA RESULT_LO\n"
"    LDA RESULT_HI\n"
"    ADC TMP_HI\n"
"    STA RESULT_HI\n"
".mul8_skip:\n"
"    ASL FACTOR_A        ; shift multiplicand left (16-bit)\n"
"    ROL TMP_HI\n"
"    DEX\n"
"    BNE .mul8_loop\n"
"    RTS\n";

/* =========================================================================
 * mul8_mega65 — hardware 8×8 multiply using MEGA65 math coprocessor
 * ========================================================================= */
static const char s_mul8_mega65[] =
"; mul8_mega65 — 8x8 = 16-bit multiply using MEGA65 hardware math unit\n"
";\n"
"; The MEGA65 math coprocessor produces the result combinatorially;\n"
"; the product is valid as soon as FACTOR_B is written to MATH_MUL_B_LO.\n"
"; Write 0 to the high-byte registers to keep this a true 8x8 operation\n"
"; (the hardware supports up to 16x16 = 32-bit).\n"
";\n"
"; PARAMS:\n"
";   FACTOR_A  = $10   ; 8-bit multiplicand\n"
";   FACTOR_B  = $11   ; 8-bit multiplier\n"
";   RESULT_LO = $12   ; product low  byte (out)\n"
";   RESULT_HI = $13   ; product high byte (out)\n"
";\n"
"; Result : [RESULT_HI:RESULT_LO] = FACTOR_A * FACTOR_B  (0..65025)\n"
"; Clobbers: A, N, Z\n"
"; Cycles  : ~16 (vs ~153 software)\n"
";\n"
"FACTOR_A     = $10\n"
"FACTOR_B     = $11\n"
"RESULT_LO    = $12\n"
"RESULT_HI    = $13\n"
"\n"
"MATH_MUL_A_LO = $D770   ; multiplicand A low byte\n"
"MATH_MUL_A_HI = $D771   ; multiplicand A high byte (clear for 8-bit)\n"
"MATH_MUL_B_LO = $D772   ; multiplicand B low byte\n"
"MATH_MUL_B_HI = $D773   ; multiplicand B high byte (clear for 8-bit)\n"
"MATH_RESULT_0 = $D778   ; result byte 0 (LSB)\n"
"MATH_RESULT_1 = $D779   ; result byte 1\n"
"\n"
"mul8_mega65:\n"
"    LDA #0\n"
"    STA MATH_MUL_A_HI   ; keep this an 8-bit operand\n"
"    STA MATH_MUL_B_HI\n"
"    LDA FACTOR_A\n"
"    STA MATH_MUL_A_LO   ; write A first\n"
"    LDA FACTOR_B\n"
"    STA MATH_MUL_B_LO   ; write B; result is immediately ready\n"
"    LDA MATH_RESULT_0\n"
"    STA RESULT_LO\n"
"    LDA MATH_RESULT_1\n"
"    STA RESULT_HI\n"
"    RTS\n";

/* =========================================================================
 * div16 — software 16÷8 = 16-bit quotient + 8-bit remainder
 * ========================================================================= */
static const char s_div16[] =
"; div16 — unsigned 16÷8 division (software, all 6502 variants)\n"
";\n"
"; Classic restoring long-division.  The 16-bit dividend is consumed\n"
"; in-place and replaced by the 16-bit quotient on exit.\n"
";\n"
"; PARAMS:\n"
";   DIVIDEND_LO = $10   ; dividend low  byte (in); quotient low  byte (out)\n"
";   DIVIDEND_HI = $11   ; dividend high byte (in); quotient high byte (out)\n"
";   DIVISOR     = $12   ; 8-bit divisor (must be non-zero)\n"
";   REMAINDER   = $13   ; 8-bit remainder (out)\n"
";\n"
"; Clobbers: A, X, N, Z, C\n"
"; Cycles  : ~320 worst-case\n"
"; Note    : quotient is 16-bit; overflow not detected.\n"
";\n"
"DIVIDEND_LO = $10\n"
"DIVIDEND_HI = $11\n"
"DIVISOR     = $12\n"
"REMAINDER   = $13\n"
"\n"
"div16:\n"
"    LDA #0\n"
"    STA REMAINDER\n"
"    LDX #16             ; 16 bit-iterations\n"
".div16_loop:\n"
"    ASL DIVIDEND_LO     ; shift dividend/quotient left (carry <- bit 15)\n"
"    ROL DIVIDEND_HI\n"
"    ROL REMAINDER       ; shift carry into remainder\n"
"    SEC\n"
"    LDA REMAINDER\n"
"    SBC DIVISOR\n"
"    BCC .div16_no_sub   ; remainder < divisor: restore\n"
"    STA REMAINDER       ; keep subtracted remainder\n"
"    INC DIVIDEND_LO     ; set quotient bit (bit 0 was just shifted in as 0)\n"
".div16_no_sub:\n"
"    DEX\n"
"    BNE .div16_loop\n"
"    RTS\n";

/* =========================================================================
 * div16_mega65 — hardware 16÷16 using MEGA65 math coprocessor
 * ========================================================================= */
static const char s_div16_mega65[] =
"; div16_mega65 — 16÷16 division using MEGA65 hardware math unit\n"
";\n"
"; The MEGA65 math coprocessor computes the result combinatorially;\n"
"; quotient and remainder are available immediately after writing the\n"
"; divisor high byte.\n"
";\n"
"; PARAMS:\n"
";   DIVIDEND_LO = $10   ; dividend low  byte\n"
";   DIVIDEND_HI = $11   ; dividend high byte\n"
";   DIVISOR_LO  = $12   ; divisor  low  byte\n"
";   DIVISOR_HI  = $13   ; divisor  high byte (0 for 16÷8)\n"
";   RESULT_LO   = $14   ; quotient  low  byte (out)\n"
";   RESULT_HI   = $15   ; quotient  high byte (out)\n"
";   REMAINDER   = $16   ; remainder low  byte (out)\n"
";\n"
"; Clobbers: A, N, Z\n"
"; Cycles  : ~20 (vs ~320 software)\n"
";\n"
"DIVIDEND_LO   = $10\n"
"DIVIDEND_HI   = $11\n"
"DIVISOR_LO    = $12\n"
"DIVISOR_HI    = $13\n"
"RESULT_LO     = $14\n"
"RESULT_HI     = $15\n"
"REMAINDER     = $16\n"
"\n"
"MATH_DIV_A_LO = $D768   ; dividend low  byte\n"
"MATH_DIV_A_HI = $D769   ; dividend high byte\n"
"MATH_DIV_B_LO = $D76A   ; divisor  low  byte\n"
"MATH_DIV_B_HI = $D76B   ; divisor  high byte\n"
"MATH_RESULT_0 = $D778   ; result byte 0 — quotient LSB\n"
"MATH_RESULT_1 = $D779   ; result byte 1 — quotient MSB\n"
"MATH_RESULT_2 = $D77A   ; result byte 2 — remainder LSB\n"
"\n"
"div16_mega65:\n"
"    LDA DIVIDEND_LO\n"
"    STA MATH_DIV_A_LO\n"
"    LDA DIVIDEND_HI\n"
"    STA MATH_DIV_A_HI\n"
"    LDA DIVISOR_LO\n"
"    STA MATH_DIV_B_LO\n"
"    LDA DIVISOR_HI\n"
"    STA MATH_DIV_B_HI   ; write completes; result ready immediately\n"
"    LDA MATH_RESULT_0\n"
"    STA RESULT_LO\n"
"    LDA MATH_RESULT_1\n"
"    STA RESULT_HI\n"
"    LDA MATH_RESULT_2\n"
"    STA REMAINDER\n"
"    RTS\n";

/* =========================================================================
 * bin_to_bcd — 8-bit binary to 3-digit BCD (subtraction loop, all 6502)
 * ========================================================================= */
static const char s_bin_to_bcd[] =
"; bin_to_bcd — convert 8-bit binary (0..255) to 3 decimal digits\n"
";\n"
"; Iterative subtraction: peel off hundreds, then tens, remainder = units.\n"
";\n"
"; PARAMS:\n"
";   INPUT    = $10   ; 8-bit binary input (preserved)\n"
";   HUNDREDS = $11   ; hundreds digit (0..2) out\n"
";   TENS     = $12   ; tens     digit (0..9) out\n"
";   UNITS    = $13   ; units    digit (0..9) out\n"
";\n"
"; Clobbers: A, X, Y, N, Z, C\n"
"; Cycles  : ~90 worst-case (value=255)\n"
";\n"
"INPUT    = $10\n"
"HUNDREDS = $11\n"
"TENS     = $12\n"
"UNITS    = $13\n"
"\n"
"bin_to_bcd:\n"
"    LDX #0\n"
"    LDY #0\n"
"    LDA INPUT\n"
".bcd_100s:\n"
"    CMP #100\n"
"    BCC .bcd_10s\n"
"    SBC #100            ; C set from CMP, so SBC = subtract without borrow\n"
"    INX\n"
"    JMP .bcd_100s\n"
".bcd_10s:\n"
"    CMP #10\n"
"    BCC .bcd_done\n"
"    SBC #10\n"
"    INY\n"
"    JMP .bcd_10s\n"
".bcd_done:\n"
"    STA UNITS\n"
"    STX HUNDREDS\n"
"    STY TENS\n"
"    RTS\n";

/* =========================================================================
 * bin_to_bcd_65c02 — 65C02 optimised: STZ, BRA, reliable decimal flags
 * ========================================================================= */
static const char s_bin_to_bcd_65c02[] =
"; bin_to_bcd_65c02 — 8-bit binary to 3-digit BCD (65C02 optimised)\n"
";\n"
"; Same subtraction algorithm as the 6502 version but uses 65C02\n"
"; instructions: STZ to zero registers and BRA for short branches.\n"
"; On 65C02 the N, Z, V flags are valid after decimal-mode ADC/SBC,\n"
"; which is exploited here to skip an explicit CMP.\n"
";\n"
"; PARAMS:\n"
";   INPUT    = $10   ; 8-bit binary input\n"
";   HUNDREDS = $11   ; hundreds digit (0..2) out\n"
";   TENS     = $12   ; tens     digit (0..9) out\n"
";   UNITS    = $13   ; units    digit (0..9) out\n"
";\n"
"; Clobbers: A, X, Y, N, Z, C\n"
";\n"
"INPUT    = $10\n"
"HUNDREDS = $11\n"
"TENS     = $12\n"
"UNITS    = $13\n"
"\n"
"bin_to_bcd_65c02:\n"
"    LDX #0\n"
"    LDY #0\n"
"    LDA INPUT\n"
".bcd_100s:\n"
"    CMP #100\n"
"    BCC .bcd_10s        ; BCC instead of JMP-to-skip (65C02: BRA available too)\n"
"    SBC #100\n"
"    INX\n"
"    BRA .bcd_100s       ; 65C02 branch-always (2-byte, no JMP needed)\n"
".bcd_10s:\n"
"    CMP #10\n"
"    BCC .bcd_done\n"
"    SBC #10\n"
"    INY\n"
"    BRA .bcd_10s\n"
".bcd_done:\n"
"    STA UNITS\n"
"    STX HUNDREDS\n"
"    STY TENS\n"
"    RTS\n";

/* =========================================================================
 * bcd_to_bin — 2-digit packed BCD to 8-bit binary
 * ========================================================================= */
static const char s_bcd_to_bin[] =
"; bcd_to_bin — convert 2 BCD digits to 8-bit binary\n"
";\n"
"; Computes: RESULT = TENS*10 + UNITS\n"
"; Uses the identity: tens*10 = tens*8 + tens*2\n"
";                            = (tens << 3) + (tens << 1)\n"
";\n"
"; PARAMS:\n"
";   TENS   = $10   ; tens   digit (0..9)\n"
";   UNITS  = $11   ; units  digit (0..9)\n"
";   RESULT = $12   ; binary result (out, 0..99)\n"
";\n"
"; Clobbers: A, N, Z, C\n"
"; Cycles  : 18\n"
";\n"
"TENS   = $10\n"
"UNITS  = $11\n"
"RESULT = $12\n"
"\n"
"bcd_to_bin:\n"
"    LDA TENS\n"
"    ASL             ; A = TENS * 2\n"
"    STA RESULT      ; save TENS * 2\n"
"    ASL             ; A = TENS * 4\n"
"    ASL             ; A = TENS * 8\n"
"    CLC\n"
"    ADC RESULT      ; A = TENS*8 + TENS*2 = TENS*10\n"
"    ADC UNITS       ; A = TENS*10 + UNITS\n"
"    STA RESULT\n"
"    RTS\n";

/* =========================================================================
 * str_out — print null-terminated string via C64 KERNAL CHROUT
 * ========================================================================= */
static const char s_str_out[] =
"; str_out — print a null-terminated PETSCII string via C64 KERNAL\n"
";\n"
"; Calls CHROUT ($FFD2) for each byte until a $00 terminator is found.\n"
"; Y register advances as index; safe for strings up to 255 bytes.\n"
"; For other platforms, replace CHROUT with your character output routine.\n"
";\n"
"; PARAMS:\n"
";   STR_LO = $10   ; low  byte of string address\n"
";   STR_HI = $11   ; high byte of string address\n"
";\n"
"; Clobbers: A, Y, N, Z\n"
"; Cycles  : 14 + 20*len  (approx, with KERNAL overhead excluded)\n"
";\n"
"STR_LO = $10\n"
"STR_HI = $11\n"
"CHROUT = $FFD2      ; C64 KERNAL — replace for other platforms\n"
"\n"
"str_out:\n"
"    LDY #0\n"
".str_loop:\n"
"    LDA (STR_LO),Y\n"
"    BEQ .str_done       ; null terminator\n"
"    JSR CHROUT\n"
"    INY\n"
"    BNE .str_loop       ; stop if Y wraps (string > 255 chars)\n"
".str_done:\n"
"    RTS\n";

/* =========================================================================
 * memcopy — copy N bytes (up to 255) from source to destination
 * ========================================================================= */
static const char s_memcopy[] =
"; memcopy — copy N bytes (1..255) from source to destination\n"
";\n"
"; Simple forward copy using indirect indexed addressing.\n"
"; Does NOT handle overlapping regions; use memmove for that.\n"
";\n"
"; PARAMS:\n"
";   SRC_LO = $10   ; source address low  byte\n"
";   SRC_HI = $11   ; source address high byte\n"
";   DST_LO = $12   ; destination address low  byte\n"
";   DST_HI = $13   ; destination address high byte\n"
";   COUNT  = $14   ; number of bytes (1..255; 0 = no-op)\n"
";\n"
"; Clobbers: A, X, Y, N, Z\n"
"; Cycles  : 5 + 15*COUNT  (approx)\n"
";\n"
"SRC_LO = $10\n"
"SRC_HI = $11\n"
"DST_LO = $12\n"
"DST_HI = $13\n"
"COUNT  = $14\n"
"\n"
"memcopy:\n"
"    LDA COUNT\n"
"    BEQ .mc_done\n"
"    TAX             ; X = byte count\n"
"    LDY #0\n"
".mc_loop:\n"
"    LDA (SRC_LO),Y\n"
"    STA (DST_LO),Y\n"
"    INY\n"
"    DEX\n"
"    BNE .mc_loop\n"
".mc_done:\n"
"    RTS\n";

/* =========================================================================
 * memfill — fill N bytes with a constant value
 * ========================================================================= */
static const char s_memfill[] =
"; memfill — fill N bytes (1..255) with a constant value\n"
";\n"
"; PARAMS:\n"
";   DST_LO = $10   ; destination address low  byte\n"
";   DST_HI = $11   ; destination address high byte\n"
";   VALUE  = $12   ; byte value to write\n"
";   COUNT  = $13   ; number of bytes (1..255; 0 = no-op)\n"
";\n"
"; Clobbers: A, X, Y, N, Z\n"
"; Cycles  : 5 + 13*COUNT  (approx)\n"
";\n"
"DST_LO = $10\n"
"DST_HI = $11\n"
"VALUE  = $12\n"
"COUNT  = $13\n"
"\n"
"memfill:\n"
"    LDA COUNT\n"
"    BEQ .mf_done\n"
"    TAX             ; X = byte count\n"
"    LDA VALUE\n"
"    LDY #0\n"
".mf_loop:\n"
"    STA (DST_LO),Y\n"
"    INY\n"
"    DEX\n"
"    BNE .mf_loop\n"
".mf_done:\n"
"    RTS\n";

/* =========================================================================
 * delay — busy-wait delay using two nested countdown loops
 * ========================================================================= */
static const char s_delay[] =
"; delay — busy-wait delay via nested countdown loops\n"
";\n"
"; Cycle formula: (OUTER * INNER * 5) + OUTER * 9 + overhead\n"
";\n"
"; Worked example (PAL C64, ~985 kHz):\n"
";   1 frame @ 50 Hz = ~19656 cycles\n"
";   OUTER=100, INNER=39 -> 100*(39*5+9)+ovhd = 100*204 = ~20400 cycles\n"
";   Tune INNER/OUTER to taste with a cycle counter.\n"
";\n"
"; For delays longer than ~130000 cycles, call multiple times or add a\n"
"; third outer loop using a zero-page counter.\n"
";\n"
"; PARAMS:\n"
";   OUTER = $10   ; outer loop count (1..255)\n"
";   INNER = $11   ; inner loop count (1..255)\n"
";\n"
"; Clobbers: X, Y, N, Z\n"
";\n"
"OUTER = $10\n"
"INNER = $11\n"
"\n"
"delay:\n"
"    LDY OUTER           ; 3c\n"
".delay_outer:\n"
"    LDX INNER           ; 3c  per outer pass\n"
".delay_inner:\n"
"    DEX                 ; 2c\n"
"    BNE .delay_inner    ; 3c taken / 2c not taken  => ~5c per inner iter\n"
"    DEY                 ; 2c\n"
"    BNE .delay_outer    ; 3c / 2c                  => ~9c outer overhead\n"
"    RTS\n";

/* =========================================================================
 * bitmap_init — initialise C64 / MEGA65 hi-res 1bpp bitmap mode
 * ========================================================================= */
static const char s_bitmap_init[] =
"; bitmap_init — initialise C64-compatible hi-res 1bpp bitmap mode\n"
";\n"
"; Configures the VIC-II for 320×200, 1 bit-per-pixel, hi-res bitmap,\n"
"; selects VIC bank 0, and fills all 1000 screen-RAM cells with $10\n"
"; (white foreground / black background).\n"
";\n"
"; Register setup:\n"
";   $DD02 = $03   CIA2 DDR: bits 0-1 as outputs (needed to select bank)\n"
";   $DD00 = $03   CIA2 Port A: %11 → VIC bank 0 ($0000-$3FFF)\n"
";   $D011 = $3B   DEN=1 BMM=1 RSEL=1 yscroll=3  (bitmap mode on)\n"
";   $D016 = $C8   MCM=0 CSEL=1 xscroll=0        (1bpp, 40 columns)\n"
";   $D018 = $18   screen @ $0400 (VM=1), bitmap @ $2000 (bit 3=1)\n"
";   $D020 = $00   border colour: black\n"
";   $D021 = $00   background colour: black\n"
";\n"
"; Memory layout:\n"
";   $0400  screen RAM  — 1000 colour bytes ($0400-$07E7)\n"
";   $2000  bitmap data — 8000 pixel bytes  ($2000-$3F3F)\n"
";\n"
"; Clobbers: A, X\n"
"; Notes   : After this call use bitmap_clear to zero the pixel data,\n"
";           then bitmap_plot / bitmap_setcell to draw.\n"
";\n"
"bitmap_init:\n"
"    LDA #$03\n"
"    STA $DD02           ; CIA2 DDR: bank bits as outputs\n"
"    STA $DD00           ; CIA2 Port A: %11 = VIC bank 0\n"
"    LDA #$3B            ; DEN BMM RSEL yscroll=3 — bitmap mode on\n"
"    STA $D011\n"
"    LDA #$C8            ; MCM=0 (1bpp), CSEL=1 (40 col), xscroll=0\n"
"    STA $D016\n"
"    LDA #$18            ; screen @ $0400 (bits 7-4=$1), bitmap @ $2000 (bit 3=1)\n"
"    STA $D018\n"
"    LDA #$00\n"
"    STA $D020           ; border: black\n"
"    STA $D021           ; background: black\n"
"    ; Fill all 1000 screen-RAM cells ($0400-$07E7) with $10\n"
"    ; $10 = white foreground (1-bits) on black background (0-bits)\n"
"    LDA #$10\n"
"    LDX #$00\n"
".bi_fill:\n"
"    STA $0400,X         ; pages $04/$05/$06 (768 bytes)\n"
"    STA $0500,X\n"
"    STA $0600,X\n"
"    INX\n"
"    BNE .bi_fill\n"
"    LDX #$00\n"
".bi_tail:\n"
"    STA $0700,X         ; remaining 232 bytes ($0700-$07E7)\n"
"    INX\n"
"    CPX #$E8\n"
"    BNE .bi_tail\n"
"    RTS\n";

/* =========================================================================
 * bitmap_plot — set, clear, or toggle a pixel in the 1bpp bitmap
 * ========================================================================= */
static const char s_bitmap_plot[] =
"; bitmap_plot — set/clear/toggle one pixel in the 320×200 1bpp bitmap\n"
";\n"
"; Uses pre-built row-base and bitmask lookup tables (see end of snippet).\n"
"; The tables must be assembled into memory before calling this routine.\n"
";\n"
"; Pixel address formula:\n"
";   byte = row_base[PY >> 3] + (PX & $F8) + (PY & 7)\n"
";   bit  = bitmask_table[PX & 7]          ($80 = leftmost)\n"
";\n"
"; PARAMS (zero page):\n"
";   PX       = $14   pixel X  (0-255; covers left 32 of 40 columns)\n"
";   PY       = $15   pixel Y  (0-199)\n"
";   PLOT_OP  = $19   0=clear  1=set  2=toggle\n"
";\n"
"; Scratch (zero page, BADDR_LO/HI must be consecutive for (ZP),Y):\n"
";   BADDR_LO = $16   computed bitmap byte address, low  (ZP pointer)\n"
";   BADDR_HI = $17   computed bitmap byte address, high\n"
";   BMASK    = $18   pixel bitmask\n"
";\n"
"; Clobbers: A, X, Y\n"
"; Cycles  : ~50\n"
"; Notes   : For pixels at X=256-319 add 1 to BADDR_HI after the table\n"
";           lookup and adjust (PX & $F8) by subtracting 256.\n"
";\n"
"PX       = $14\n"
"PY       = $15\n"
"BADDR_LO = $16\n"
"BADDR_HI = $17\n"
"BMASK    = $18\n"
"PLOT_OP  = $19\n"
"\n"
"ROW_LO_TBL = $0800   ; 25 row-base address low  bytes\n"
"ROW_HI_TBL = $0819   ; 25 row-base address high bytes  ($0800 + 25)\n"
"BMASK_TBL  = $0832   ; 8  pixel bitmask bytes          ($0800 + 50)\n"
"\n"
"bitmap_plot:\n"
"    ; row = PY >> 3 → X; load row base address from tables\n"
"    LDA PY\n"
"    LSR\n"
"    LSR\n"
"    LSR\n"
"    TAX\n"
"    LDA ROW_LO_TBL,X\n"
"    STA BADDR_LO\n"
"    LDA ROW_HI_TBL,X\n"
"    STA BADDR_HI\n"
"    ; add column-byte offset: PX & $F8  (= col * 8)\n"
"    LDA PX\n"
"    AND #$F8\n"
"    CLC\n"
"    ADC BADDR_LO\n"
"    STA BADDR_LO\n"
"    BCC .bplot_nc1\n"
"    INC BADDR_HI\n"
".bplot_nc1:\n"
"    ; add scanline within cell: PY & 7\n"
"    LDA PY\n"
"    AND #$07\n"
"    CLC\n"
"    ADC BADDR_LO\n"
"    STA BADDR_LO\n"
"    BCC .bplot_nc2\n"
"    INC BADDR_HI\n"
".bplot_nc2:\n"
"    ; bitmask from table: $80 >> (PX & 7)\n"
"    LDA PX\n"
"    AND #$07\n"
"    TAX\n"
"    LDA BMASK_TBL,X\n"
"    STA BMASK\n"
"    ; apply pixel operation\n"
"    LDY #0\n"
"    LDA PLOT_OP\n"
"    BNE .bplot_not_clear\n"
"    LDA BMASK\n"
"    EOR #$FF            ; ~mask: AND clears the bit\n"
"    AND (BADDR_LO),Y\n"
"    STA (BADDR_LO),Y\n"
"    RTS\n"
".bplot_not_clear:\n"
"    CMP #2\n"
"    BNE .bplot_set\n"
"    LDA BMASK\n"
"    EOR (BADDR_LO),Y    ; toggle\n"
"    STA (BADDR_LO),Y\n"
"    RTS\n"
".bplot_set:\n"
"    LDA BMASK\n"
"    ORA (BADDR_LO),Y    ; set\n"
"    STA (BADDR_LO),Y\n"
"    RTS\n"
"\n"
"; Lookup tables — place at $0800 (25+25+8 = 58 bytes)\n"
"; row_base[i] = $2000 + i*320  for i = 0..24\n"
";\n"
";  i  address  lo  hi     i  address  lo  hi\n"
";  0  $2000   $00 $20    13  $3040   $40 $30\n"
";  1  $2140   $40 $21    14  $3180   $80 $31\n"
";  2  $2280   $80 $22    15  $32C0   $C0 $32\n"
";  3  $23C0   $C0 $23    16  $3400   $00 $34\n"
";  4  $2500   $00 $25    17  $3540   $40 $35\n"
";  5  $2640   $40 $26    18  $3680   $80 $36\n"
";  6  $2780   $80 $27    19  $37C0   $C0 $37\n"
";  7  $28C0   $C0 $28    20  $3900   $00 $39\n"
";  8  $2A00   $00 $2A    21  $3A40   $40 $3A\n"
";  9  $2B40   $40 $2B    22  $3B80   $80 $3B\n"
"; 10  $2C80   $80 $2C    23  $3CC0   $C0 $3C\n"
"; 11  $2DC0   $C0 $2D    24  $3E00   $00 $3E\n"
"; 12  $2F00   $00 $2F\n"
".org $0800\n"
"row_base_lo:\n"
".byte $00,$40,$80,$C0,$00,$40,$80,$C0,$00,$40,$80,$C0,$00\n"
".byte $40,$80,$C0,$00,$40,$80,$C0,$00,$40,$80,$C0,$00\n"
"row_base_hi:\n"
".byte $20,$21,$22,$23,$25,$26,$27,$28,$2A,$2B,$2C,$2D,$2F\n"
".byte $30,$31,$32,$34,$35,$36,$37,$39,$3A,$3B,$3C,$3E\n"
"bitmask_table:\n"
".byte $80,$40,$20,$10,$08,$04,$02,$01\n";

/* =========================================================================
 * bitmap_setcell — set 8×8 cell foreground / background colour
 * ========================================================================= */
static const char s_bitmap_setcell[] =
"; bitmap_setcell — set the colour of an 8x8 cell in screen RAM\n"
";\n"
"; In C64 hi-res bitmap mode each screen RAM byte controls one 8x8 cell:\n"
";   bits 7-4 = foreground colour index (for '1' / set pixels)\n"
";   bits 3-0 = background colour index (for '0' / clear pixels)\n"
";\n"
"; Screen RAM address = $0400 + CELL_Y * 40 + CELL_X\n"
";\n"
"; CELL_Y * 40 is decomposed as CELL_Y*32 + CELL_Y*8 to avoid overflow:\n"
";   lo = (CELL_Y & 7)*32 + CELL_Y*8   (carry → hi)\n"
";   hi = (CELL_Y >> 3)   + carry\n"
";\n"
"; PARAMS (zero page):\n"
";   CELL_X = $10   column index (0-39)\n"
";   CELL_Y = $11   row    index (0-24)\n"
";   FG_COL = $12   foreground colour (0-15)\n"
";   BG_COL = $13   background colour (0-15)\n"
";\n"
"; Scratch (consecutive pair for (ZP),Y indirect):\n"
";   ROW_LO = $20   computed cell address, low  (ZP pointer)\n"
";   ROW_HI = $21   computed cell address, high\n"
";   TEMP_R = $22   scratch byte\n"
";\n"
"; Clobbers: A, Y\n"
"; Cycles  : ~65\n"
";\n"
"CELL_X = $10\n"
"CELL_Y = $11\n"
"FG_COL = $12\n"
"BG_COL = $13\n"
"ROW_LO = $20\n"
"ROW_HI = $21\n"
"TEMP_R = $22\n"
"\n"
"bitmap_setcell:\n"
"    ; CELL_Y * 40 = CELL_Y*32 + CELL_Y*8\n"
"    LDA CELL_Y\n"
"    LSR\n"
"    LSR\n"
"    LSR\n"
"    STA TEMP_R          ; TEMP_R = CELL_Y >> 3  (high-byte seed)\n"
"    LDA CELL_Y\n"
"    AND #$07\n"
"    ASL                 ; (CELL_Y & 7) * 2\n"
"    ASL                 ; * 4\n"
"    ASL                 ; * 8\n"
"    ASL                 ; * 16\n"
"    ASL                 ; * 32  (max 7*32=224, fits in 8 bits)\n"
"    STA ROW_LO\n"
"    LDA CELL_Y\n"
"    ASL                 ; CELL_Y * 2\n"
"    ASL                 ; * 4\n"
"    ASL                 ; * 8   (max 24*8=192, fits in 8 bits)\n"
"    CLC\n"
"    ADC ROW_LO          ; CELL_Y*8 + (CELL_Y & 7)*32  = lo(CELL_Y*40)\n"
"    STA ROW_LO\n"
"    LDA TEMP_R\n"
"    ADC #0              ; carry from above addition\n"
"    STA ROW_HI          ; hi(CELL_Y*40)\n"
"    ; add CELL_X\n"
"    LDA CELL_X\n"
"    CLC\n"
"    ADC ROW_LO\n"
"    STA ROW_LO\n"
"    BCC .bsc_ok\n"
"    INC ROW_HI\n"
".bsc_ok:\n"
"    ; add SCREEN_BASE $0400 — high byte only (low byte is $00)\n"
"    LDA #$04            ; (*) high byte of SCREEN_BASE $0400\n"
"    CLC\n"
"    ADC ROW_HI\n"
"    STA ROW_HI\n"
"    ; pack colour byte: (FG_COL << 4) | BG_COL\n"
"    LDA FG_COL          ; must be 0-15\n"
"    ASL\n"
"    ASL\n"
"    ASL\n"
"    ASL                 ; FG_COL shifted to bits 7-4\n"
"    ORA BG_COL          ; BG_COL in bits 3-0\n"
"    LDY #0\n"
"    STA (ROW_LO),Y\n"
"    RTS\n";

/* =========================================================================
 * bitmap_clear — zero all 8000 bytes of the 320×200 bitmap (software)
 * ========================================================================= */
static const char s_bitmap_clear[] =
"; bitmap_clear — zero the 320×200 hi-res bitmap (software loop)\n"
";\n"
"; Clears 8000 bytes = 31 full 256-byte pages + 64 remaining bytes.\n"
";\n"
"; PARAMS:\n"
";   PTR_LO = $10   ZP pointer low  (must be consecutive with PTR_HI)\n"
";   PTR_HI = $11   ZP pointer high\n"
";\n"
"; Initialised here to BITMAP_BASE $2000.\n"
";   (*) Update the two literal bytes for a different BITMAP_BASE.\n"
";\n"
"; Clobbers: A, X, Y\n"
"; Cycles  : ~48000  (~48 ms at 1 MHz; use bitmap_clear_mega65 for speed)\n"
";\n"
"PTR_LO = $10\n"
"PTR_HI = $11\n"
"\n"
"bitmap_clear:\n"
"    LDA #$00            ; (*) low  byte of BITMAP_BASE $2000\n"
"    STA PTR_LO\n"
"    LDA #$20            ; (*) high byte of BITMAP_BASE $2000\n"
"    STA PTR_HI\n"
"    LDA #0\n"
"    LDX #31             ; 31 full 256-byte pages  (31*256 = 7936 bytes)\n"
".bclr_pages:\n"
"    LDY #0\n"
".bclr_page:\n"
"    STA (PTR_LO),Y\n"
"    INY\n"
"    BNE .bclr_page      ; inner: 256 bytes per page (Y wraps 0→0)\n"
"    INC PTR_HI\n"
"    DEX\n"
"    BNE .bclr_pages\n"
"    ; remaining 64 bytes  (8000 - 7936 = 64)\n"
"    LDY #63\n"
".bclr_last:\n"
"    STA (PTR_LO),Y\n"
"    DEY\n"
"    BPL .bclr_last      ; branch while Y >= 0  (stores Y=63..0)\n"
"    RTS\n";

/* =========================================================================
 * bitmap_clear_mega65 — zero the bitmap in one DMA fill (~8000 cycles)
 * ========================================================================= */
static const char s_bitmap_clear_mega65[] =
"; bitmap_clear_mega65 — zero the 320×200 bitmap using MEGA65 enhanced DMA\n"
";\n"
"; ~6× faster than the software bitmap_clear: ~8000 DMA cycles vs ~48000.\n"
"; Fires a single DMA FILL job: 8000 ($1F40) bytes written with $00.\n"
";\n"
"; Job list placed at $1FD0 via .org below.\n"
";   (*) Update the trigger literals and .org address together if\n"
";       relocating the job list.\n"
";   (*) Update bytes at offsets +8 / +9 in bm_clr_job if changing\n"
";       BITMAP_BASE away from $2000.\n"
";\n"
"; Clobbers: A\n"
"; Cycles  : ~24 setup + ~8000 DMA\n"
";\n"
"DMA_ADDRHI   = $D701   ; job-list bits  8-15\n"
"DMA_ADDRMID  = $D702   ; job-list bits 16-23\n"
"DMA_ADDRMBHI = $D704   ; job-list bits 24-27\n"
"DMA_TRIGGER  = $D705   ; write bits 0-7 here to trigger enhanced DMA\n"
"\n"
"bitmap_clear_mega65:\n"
"    LDA #$1F             ; (*) high byte of job-list address $1FD0\n"
"    STA DMA_ADDRHI\n"
"    LDA #$00\n"
"    STA DMA_ADDRMID\n"
"    STA DMA_ADDRMBHI\n"
"    LDA #$D0             ; (*) low  byte of job-list address $1FD0\n"
"    STA DMA_TRIGGER\n"
"    RTS\n"
"\n"
"; DMA job list — FILL 8000 bytes at $2000 with $00\n"
".org $1FD0\n"
"bm_clr_job:\n"
"    .byte $0B, $00       ; option: 12-byte record; end of tokens\n"
"    .byte $03            ; command: FILL (bits 1:0=%11), no chain\n"
"    .byte $40, $1F       ; count: $1F40 = 8000 bytes (lo, hi)\n"
"    .byte $00            ; fill value: $00 (clear to black)\n"
"    .byte $00, $00       ; source bits 8-15, 16-19 (unused in fill mode)\n"
"    .byte $00            ; (*) destination bits  0-7  of BITMAP_BASE $2000\n"
"    .byte $20            ; (*) destination bits  8-15 of BITMAP_BASE $2000\n"
"    .byte $00            ; destination bits 16-19 (0 = first 64KB)\n"
"    .byte $00            ; options: dst linear (bits 3:2=%00)\n"
"    .byte $00, $00       ; reserved\n";

/* =========================================================================
 * dma_copy — bulk copy using MEGA65 enhanced DMA ($D705 trigger)
 * ========================================================================= */
static const char s_dma_copy[] =
"; dma_copy — copy N bytes using MEGA65 enhanced DMA\n"
";\n"
"; Bulk-copies memory at ~1 cycle/byte vs ~15 cycles/byte for a software\n"
"; loop.  Builds a 14-byte enhanced DMA job list at JOB_BASE ($1FF0) then\n"
"; fires the $D705 physical-address trigger.\n"
";\n"
"; MEGA65 $D705 trigger sequence:\n"
";   1. Write bits  8-15 of job-list address to $D701\n"
";   2. Write bits 16-23 of job-list address to $D702\n"
";   3. Write bits 24-27 of job-list address to $D704\n"
";   4. Write bits  0-7  of job-list address to $D705  <- fires DMA\n"
";\n"
"; Job record layout (12 bytes, after 2-byte option prefix $0B $00):\n"
";   [0] command   : 00 = copy, 03 = fill; bit 2 = chain next job\n"
";   [1-2] count   : bytes to transfer (little-endian; 0 = 65536)\n"
";   [3]   src_lo  : source bits  0-7\n"
";   [4]   src_mid : source bits  8-15\n"
";   [5]   src_hi  : source bits 16-19 (low nibble); bit 6 = backwards\n"
";   [6]   dst_lo  : destination bits  0-7\n"
";   [7]   dst_mid : destination bits  8-15\n"
";   [8]   dst_hi  : destination bits 16-19 (low nibble)\n"
";   [9]   options : bits 1:0 = src mode (00=linear, 01=hold)\n"
";                   bits 3:2 = dst mode (00=linear, 01=hold)\n"
";   [10-11] reserved\n"
";\n"
"; PARAMS (zero page):\n"
";   SRC_LO = $10   ; source address low  byte\n"
";   SRC_HI = $11   ; source address high byte\n"
";   DST_LO = $12   ; destination address low  byte\n"
";   DST_HI = $13   ; destination address high byte\n"
";   CNT_LO = $14   ; byte count low  byte (0 means 65536)\n"
";   CNT_HI = $15   ; byte count high byte\n"
";\n"
"; JOB_BASE = $1FF0: 14-byte scratch area for the DMA job list.\n"
";   To use a different address, change JOB_BASE and update all $1FFx\n"
";   literals below, plus the (*)-marked trigger bytes.\n"
";\n"
"; Clobbers: A\n"
"; Cycles  : ~54 setup + 1 per byte copied\n"
";\n"
"SRC_LO = $10\n"
"SRC_HI = $11\n"
"DST_LO = $12\n"
"DST_HI = $13\n"
"CNT_LO = $14\n"
"CNT_HI = $15\n"
"\n"
"JOB_BASE     = $1FF0   ; job-list scratch area (change + update literals)\n"
"DMA_ADDRHI   = $D701   ; job-list bits  8-15\n"
"DMA_ADDRMID  = $D702   ; job-list bits 16-23\n"
"DMA_ADDRMBHI = $D704   ; job-list bits 24-27\n"
"DMA_TRIGGER  = $D705   ; write bits 0-7 here to trigger enhanced DMA\n"
"\n"
"dma_copy:\n"
"    ; Build enhanced DMA job list at JOB_BASE ($1FF0)\n"
"    LDA #$0B\n"
"    STA $1FF0            ; option token: use 12-byte record format\n"
"    LDA #$00\n"
"    STA $1FF1            ; end of option tokens\n"
"    STA $1FF2            ; command: COPY (bits 1:0=%00), chain=0\n"
"    LDA CNT_LO\n"
"    STA $1FF3            ; count low  byte\n"
"    LDA CNT_HI\n"
"    STA $1FF4            ; count high byte (0 = 65536)\n"
"    LDA SRC_LO\n"
"    STA $1FF5            ; source bits  0-7\n"
"    LDA SRC_HI\n"
"    STA $1FF6            ; source bits  8-15\n"
"    LDA #$00\n"
"    STA $1FF7            ; source bits 16-19 (0 = first 64KB)\n"
"    LDA DST_LO\n"
"    STA $1FF8            ; destination bits  0-7\n"
"    LDA DST_HI\n"
"    STA $1FF9            ; destination bits  8-15\n"
"    LDA #$00\n"
"    STA $1FFA            ; destination bits 16-19 (0 = first 64KB)\n"
"    STA $1FFB            ; options: src linear (00), dst linear (00)\n"
"    STA $1FFC            ; reserved\n"
"    STA $1FFD            ; reserved\n"
"    ; Trigger enhanced DMA — point $D701/$D705 at JOB_BASE\n"
"    LDA #$1F             ; (*) high byte of JOB_BASE $1FF0\n"
"    STA DMA_ADDRHI\n"
"    LDA #$00\n"
"    STA DMA_ADDRMID\n"
"    STA DMA_ADDRMBHI\n"
"    LDA #$F0             ; (*) low  byte of JOB_BASE $1FF0\n"
"    STA DMA_TRIGGER      ; write last — fires DMA immediately\n"
"    RTS\n";

/* =========================================================================
 * dma_fill — fill N bytes with a constant using MEGA65 enhanced DMA
 * ========================================================================= */
static const char s_dma_fill[] =
"; dma_fill — fill N bytes with a constant using MEGA65 enhanced DMA\n"
";\n"
"; Writes FILL_VAL to FILL_COUNT bytes starting at DST.  ~1 cycle/byte;\n"
"; ideal for screen clears, zero-filling buffers, attribute fills, etc.\n"
";\n"
"; Uses the FILL command (bits 1:0=%11 in the command byte).  The fill\n"
"; value is placed in the source-address byte 0 field of the job record.\n"
";\n"
"; PARAMS (zero page):\n"
";   FILL_VAL = $10   ; byte value to fill with\n"
";   DST_LO   = $11   ; destination address low  byte\n"
";   DST_HI   = $12   ; destination address high byte\n"
";   CNT_LO   = $13   ; byte count low  byte (0 means 65536)\n"
";   CNT_HI   = $14   ; byte count high byte\n"
";\n"
"; JOB_BASE = $1FE0: 14-byte scratch area (change $1FEx literals + (*) below).\n"
";\n"
"; Clobbers: A\n"
"; Cycles  : ~48 setup + 1 per byte filled\n"
";\n"
"FILL_VAL = $10\n"
"DST_LO   = $11\n"
"DST_HI   = $12\n"
"CNT_LO   = $13\n"
"CNT_HI   = $14\n"
"\n"
"JOB_BASE     = $1FE0   ; job-list scratch area\n"
"DMA_ADDRHI   = $D701\n"
"DMA_ADDRMID  = $D702\n"
"DMA_ADDRMBHI = $D704\n"
"DMA_TRIGGER  = $D705\n"
"\n"
"dma_fill:\n"
"    ; Build enhanced DMA job list at JOB_BASE ($1FE0)\n"
"    LDA #$0B\n"
"    STA $1FE0            ; option token: use 12-byte record format\n"
"    LDA #$00\n"
"    STA $1FE1            ; end of option tokens\n"
"    LDA #$03\n"
"    STA $1FE2            ; command: FILL (bits 1:0=%11), chain=0\n"
"    LDA CNT_LO\n"
"    STA $1FE3            ; count low  byte\n"
"    LDA CNT_HI\n"
"    STA $1FE4            ; count high byte (0 = 65536)\n"
"    LDA FILL_VAL\n"
"    STA $1FE5            ; fill value (source byte 0 in fill mode)\n"
"    LDA #$00\n"
"    STA $1FE6            ; source bits  8-15 (unused in fill mode)\n"
"    STA $1FE7            ; source bits 16-19, flags (unused in fill mode)\n"
"    LDA DST_LO\n"
"    STA $1FE8            ; destination bits  0-7\n"
"    LDA DST_HI\n"
"    STA $1FE9            ; destination bits  8-15\n"
"    LDA #$00\n"
"    STA $1FEA            ; destination bits 16-19 (0 = first 64KB)\n"
"    STA $1FEB            ; options: dst linear (bits 3:2=%00)\n"
"    STA $1FEC            ; reserved\n"
"    STA $1FED            ; reserved\n"
"    ; Trigger enhanced DMA\n"
"    LDA #$1F             ; (*) high byte of JOB_BASE $1FE0\n"
"    STA DMA_ADDRHI\n"
"    LDA #$00\n"
"    STA DMA_ADDRMID\n"
"    STA DMA_ADDRMBHI\n"
"    LDA #$E0             ; (*) low  byte of JOB_BASE $1FE0\n"
"    STA DMA_TRIGGER\n"
"    RTS\n";

/* =========================================================================
 * dma_copy_far — 28-bit copy using MEGA65 DMA Memory Block (MB) tokens
 * ========================================================================= */
static const char s_dma_copy_far[] =
"; dma_copy_far — copy between 28-bit MEGA65 addresses using DMA\n"
";\n"
"; Extends dma_copy with Memory Block (MB) option tokens to reach the\n"
"; full 28-bit MEGA65 address space (Attic RAM, Colour RAM, ROM, etc.).\n"
";\n"
"; 28-bit address construction:\n"
";   full_addr = (MB << 20) | (bits_16_19 << 16) | (bits_8_15 << 8) | bits_0_7\n"
";   MB option token $80 <byte>  sets source      bits 20-27\n"
";   MB option token $81 <byte>  sets destination bits 20-27\n"
";\n"
"; Common MEGA65 memory areas (28-bit):\n"
";   $0000000 - $007FFFF   Chip RAM (512 KB)\n"
";   $0800000 - $0EFFFFF   Attic RAM (model-dependent, up to ~110 MB)\n"
";   $FF80000              VIC-IV colour RAM (2 KB)\n"
";\n"
"; This example copies $0100 bytes from Attic RAM $0800000\n"
"; to Chip RAM $0000000.  Adjust MB values and record bytes for your\n"
"; source and destination.\n"
";\n"
"; The job list is placed at $1FB0 via .org.\n"
";   To relocate: change the .org address and the (*)-marked literals.\n"
";\n"
"; Clobbers: A\n"
"; Cycles  : ~24 setup + 1 per byte copied\n"
";\n"
"DMA_ADDRHI   = $D701\n"
"DMA_ADDRMID  = $D702\n"
"DMA_ADDRMBHI = $D704\n"
"DMA_TRIGGER  = $D705\n"
"\n"
"dma_copy_far:\n"
"    LDA #$1F             ; (*) high byte of job-list address $1FB0\n"
"    STA DMA_ADDRHI\n"
"    LDA #$00\n"
"    STA DMA_ADDRMID\n"
"    STA DMA_ADDRMBHI\n"
"    LDA #$B0             ; (*) low  byte of job-list address $1FB0\n"
"    STA DMA_TRIGGER      ; fires DMA\n"
"    RTS\n"
"\n"
"; DMA job list with 28-bit (MB) option tokens — placed at $1FB0\n"
".org $1FB0\n"
"dma_far_job:\n"
"    .byte $0B            ; option: use 12-byte record format\n"
"    .byte $80, $08       ; source MB = $08 → src bits 20-27\n"
"                         ;   combined with record bytes: src = $0800000\n"
"    .byte $81, $00       ; destination MB = $00 → dst bits 20-27 = 0\n"
"                         ;   combined with record bytes: dst = $0000000\n"
"    .byte $00            ; end of option tokens\n"
"    .byte $00            ; command: COPY (bits 1:0=%00), no chain\n"
"    .byte $00, $01       ; count: $0100 = 256 bytes (lo, hi)\n"
"    .byte $00            ; source bits  0-7  (of $0800000 after MB)\n"
"    .byte $00            ; source bits  8-15\n"
"    .byte $00            ; source bits 16-19 (low nibble); bit 6 = backwards\n"
"    .byte $00            ; destination bits  0-7\n"
"    .byte $00            ; destination bits  8-15\n"
"    .byte $00            ; destination bits 16-19\n"
"    .byte $00            ; options: src linear (bits 1:0=%00), dst linear\n"
"    .byte $00            ; reserved\n"
"    .byte $00            ; reserved\n";

/* =========================================================================
 * sprite_init
 * ========================================================================= */
static const char s_sprite_init[] =
"; sprite_init — full VIC-II sprite initialisation\n"
";\n"
"; Sets position, X MSB, enables sprite, sets colour and data block pointer.\n"
";\n"
"; PARAMS — change these equates to suit your layout:\n"
";   SPRITE_NUM = sprite number 0-7\n"
";   SPR_X_LO   = sprite X low byte  (0-255; set SPR_X_HI=$01 if X > 255)\n"
";   SPR_X_HI   = sprite X high bit  ($00 or $01)\n"
";   SPR_Y      = sprite Y position  (0-255)\n"
";   SPR_COLOR  = sprite colour      (0-15)\n"
";   SPR_PTR    = data block pointer (sprite_data_address / 64)\n"
";   BIT_MASK   = scratch byte       (holds computed 1<<SPRITE_NUM)\n"
";\n"
"; Clobbers: A, X\n"
";\n"
"SPRITE_NUM = $10\n"
"SPR_X_LO   = $11\n"
"SPR_X_HI   = $12\n"
"SPR_Y      = $13\n"
"SPR_COLOR  = $14\n"
"SPR_PTR    = $15\n"
"BIT_MASK   = $16\n"
"\n"
"sprite_init:\n"
"    ; compute BIT_MASK = 1 << SPRITE_NUM\n"
"    LDA #1\n"
"    LDX SPRITE_NUM\n"
"    BEQ .si_got_mask\n"
".si_shift:\n"
"    ASL\n"
"    DEX\n"
"    BNE .si_shift\n"
".si_got_mask:\n"
"    STA BIT_MASK\n"
"\n"
"    ; set X / Y position ($D000+N*2 = X lo, $D001+N*2 = Y)\n"
"    LDA SPRITE_NUM\n"
"    ASL\n"
"    TAX\n"
"    LDA SPR_X_LO\n"
"    STA $D000,X\n"
"    LDA SPR_Y\n"
"    STA $D001,X\n"
"\n"
"    ; update X MSB bit in $D010 (read-modify-write)\n"
"    LDA SPR_X_HI\n"
"    AND #$01\n"
"    BEQ .si_x_clear\n"
"    LDA $D010\n"
"    ORA BIT_MASK          ; set bit — result always non-zero, BNE always taken\n"
"    BNE .si_x_done\n"
".si_x_clear:\n"
"    LDA BIT_MASK\n"
"    EOR #$FF\n"
"    AND $D010             ; clear bit\n"
".si_x_done:\n"
"    STA $D010\n"
"\n"
"    ; enable sprite in $D015\n"
"    LDA $D015\n"
"    ORA BIT_MASK\n"
"    STA $D015\n"
"\n"
"    ; colour ($D027+N) and data block pointer ($07F8+N)\n"
"    LDX SPRITE_NUM\n"
"    LDA SPR_COLOR\n"
"    STA $D027,X\n"
"    LDA SPR_PTR\n"
"    STA $07F8,X\n"
"    RTS\n";

/* =========================================================================
 * sprite_move
 * ========================================================================= */
static const char s_sprite_move[] =
"; sprite_move — update VIC-II sprite position (X + Y + X MSB)\n"
";\n"
"; Fast position-only update; does not touch enable, colour, or pointer.\n"
";\n"
"; PARAMS:\n"
";   SPRITE_NUM = sprite number 0-7\n"
";   SPR_X_LO   = sprite X low byte\n"
";   SPR_X_HI   = sprite X high bit ($00 or $01)\n"
";   SPR_Y      = sprite Y position\n"
";   BIT_MASK   = scratch byte (holds computed 1<<SPRITE_NUM)\n"
";\n"
"; Clobbers: A, X\n"
";\n"
"SPRITE_NUM = $10\n"
"SPR_X_LO   = $11\n"
"SPR_X_HI   = $12\n"
"SPR_Y      = $13\n"
"BIT_MASK   = $14\n"
"\n"
"sprite_move:\n"
"    ; compute BIT_MASK = 1 << SPRITE_NUM\n"
"    LDA #1\n"
"    LDX SPRITE_NUM\n"
"    BEQ .smv_got_mask\n"
".smv_shift:\n"
"    ASL\n"
"    DEX\n"
"    BNE .smv_shift\n"
".smv_got_mask:\n"
"    STA BIT_MASK\n"
"\n"
"    ; set X / Y position\n"
"    LDA SPRITE_NUM\n"
"    ASL\n"
"    TAX\n"
"    LDA SPR_X_LO\n"
"    STA $D000,X\n"
"    LDA SPR_Y\n"
"    STA $D001,X\n"
"\n"
"    ; update X MSB bit in $D010\n"
"    LDA SPR_X_HI\n"
"    AND #$01\n"
"    BEQ .smv_x_clear\n"
"    LDA $D010\n"
"    ORA BIT_MASK          ; set bit — result always non-zero, BNE always taken\n"
"    BNE .smv_x_done\n"
".smv_x_clear:\n"
"    LDA BIT_MASK\n"
"    EOR #$FF\n"
"    AND $D010             ; clear bit\n"
".smv_x_done:\n"
"    STA $D010\n"
"    RTS\n";

/* =========================================================================
 * sprite_setcolor
 * ========================================================================= */
static const char s_sprite_setcolor[] =
"; sprite_setcolor — set a VIC-II sprite's foreground colour\n"
";\n"
"; PARAMS:\n"
";   SPRITE_NUM = sprite number 0-7\n"
";   SPR_COLOR  = colour index 0-15\n"
";\n"
"; Clobbers: A, X\n"
"; Cycles  : 10\n"
";\n"
"SPRITE_NUM = $10\n"
"SPR_COLOR  = $11\n"
"\n"
"sprite_setcolor:\n"
"    LDX SPRITE_NUM\n"
"    LDA SPR_COLOR\n"
"    STA $D027,X\n"
"    RTS\n";

/* =========================================================================
 * sprite_mc_init
 * ========================================================================= */
static const char s_sprite_mc_init[] =
"; sprite_mc_init — enable VIC-II multicolour mode for one sprite\n"
";\n"
"; Sets $D01C (multicolor enable bit), $D027+N (individual colour),\n"
"; $D025 (shared MC0) and $D026 (shared MC1).\n"
";\n"
"; In multicolour mode the sprite pixels are 2 bits wide (double width):\n"
";   %00 = transparent,  %01 = $D025 (MC0),\n"
";   %11 = $D026 (MC1),  %10 = $D027+N (individual colour)\n"
";\n"
"; PARAMS:\n"
";   SPRITE_NUM = sprite number 0-7\n"
";   SPR_COLOR  = sprite individual colour (0-15)\n"
";   MC_COLOR0  = shared multicolour 0 for $D025 (0-15)\n"
";   MC_COLOR1  = shared multicolour 1 for $D026 (0-15)\n"
";   BIT_MASK   = scratch byte (holds computed 1<<SPRITE_NUM)\n"
";\n"
"; Clobbers: A, X\n"
";\n"
"SPRITE_NUM = $10\n"
"SPR_COLOR  = $11\n"
"MC_COLOR0  = $12\n"
"MC_COLOR1  = $13\n"
"BIT_MASK   = $14\n"
"\n"
"sprite_mc_init:\n"
"    ; compute BIT_MASK = 1 << SPRITE_NUM\n"
"    LDA #1\n"
"    LDX SPRITE_NUM\n"
"    BEQ .smc_got_mask\n"
".smc_shift:\n"
"    ASL\n"
"    DEX\n"
"    BNE .smc_shift\n"
".smc_got_mask:\n"
"    STA BIT_MASK\n"
"\n"
"    ; enable multicolour for this sprite\n"
"    LDA $D01C\n"
"    ORA BIT_MASK\n"
"    STA $D01C\n"
"\n"
"    ; individual and shared colours\n"
"    LDX SPRITE_NUM\n"
"    LDA SPR_COLOR\n"
"    STA $D027,X\n"
"    LDA MC_COLOR0\n"
"    STA $D025\n"
"    LDA MC_COLOR1\n"
"    STA $D026\n"
"    RTS\n";

/* =========================================================================
 * sprite_data
 * ========================================================================= */
static const char s_sprite_data[] =
"; sprite_data — 64-byte diamond sprite shape\n"
";\n"
"; Assembled at $2080 → block pointer = $82  (= $2080 / 64).\n"
"; Pass SPR_PTR = $82 to sprite_init to select this shape.\n"
";\n"
"; Layout: 21 rows * 3 bytes + 1 padding byte = 64 bytes.\n"
";\n"
".org $2080\n"
"spr_diamond:\n"
"    .byte $00,$18,$00   ; row  0  (2px wide)\n"
"    .byte $00,$3C,$00   ; row  1  (4px)\n"
"    .byte $00,$7E,$00   ; row  2  (6px)\n"
"    .byte $00,$FF,$00   ; row  3  (8px)\n"
"    .byte $01,$FF,$80   ; row  4  (10px)\n"
"    .byte $03,$FF,$C0   ; row  5  (12px)\n"
"    .byte $07,$FF,$E0   ; row  6  (14px)\n"
"    .byte $0F,$FF,$F0   ; row  7  (16px)\n"
"    .byte $1F,$FF,$F8   ; row  8  (18px)\n"
"    .byte $3F,$FF,$FC   ; row  9  (20px)\n"
"    .byte $7F,$FF,$FE   ; row 10  (22px, widest)\n"
"    .byte $3F,$FF,$FC   ; row 11  (20px)\n"
"    .byte $1F,$FF,$F8   ; row 12  (18px)\n"
"    .byte $0F,$FF,$F0   ; row 13  (16px)\n"
"    .byte $07,$FF,$E0   ; row 14  (14px)\n"
"    .byte $03,$FF,$C0   ; row 15  (12px)\n"
"    .byte $01,$FF,$80   ; row 16  (10px)\n"
"    .byte $00,$FF,$00   ; row 17  (8px)\n"
"    .byte $00,$7E,$00   ; row 18  (6px)\n"
"    .byte $00,$3C,$00   ; row 19  (4px)\n"
"    .byte $00,$18,$00   ; row 20  (2px)\n"
"    .byte $00            ; padding (byte 63)\n";

/* =========================================================================
 * sprite_mega65_16col
 * ========================================================================= */
static const char s_sprite_mega65_16col[] =
"; sprite_mega65_16col — enable MEGA65 VIC-IV 16-colour mode for one sprite\n"
";\n"
"; Sets bit N in $D04B to switch sprite N from 1bpp (2-colour) to 4bpp\n"
"; (16-colour) mode. Each sprite pixel becomes 4 bits wide, giving full\n"
"; 16-colour sprites at half the horizontal resolution.\n"
";\n"
"; PARAMS:\n"
";   SPRITE_NUM = sprite number 0-7 (zero page)\n"
";\n"
"; Clobbers: A, X\n"
";\n"
"SPRITE_NUM = $10\n"
"\n"
"sprite_mega65_16col:\n"
"    ; compute 1 << SPRITE_NUM\n"
"    LDA #1\n"
"    LDX SPRITE_NUM\n"
"    BEQ .s16_got_mask\n"
".s16_shift:\n"
"    ASL\n"
"    DEX\n"
"    BNE .s16_shift\n"
".s16_got_mask:\n"
"    ORA $D04B             ; set the sprite's 16-colour enable bit\n"
"    STA $D04B\n"
"    RTS\n";

/* =========================================================================
 * Snippet table
 * ========================================================================= */
const snippet_t g_snippets[] = {
    /* name              category   summary                                       processor  requires_device  body */
    { "add16",           "math",    "16-bit addition (zero-page)",                "6502",    NULL,            s_add16           },
    { "sub16",           "math",    "16-bit subtraction (zero-page)",             "6502",    NULL,            s_sub16           },
    { "mul8",            "math",    "8x8 = 16-bit multiply (software)",           "6502",    NULL,            s_mul8            },
    { "mul8_mega65",     "math",    "8x8 = 16-bit multiply (MEGA65 hardware)",    "45gs02",  "mega65_math",   s_mul8_mega65     },
    { "div16",           "math",    "16/8 = 16-bit quotient + 8-bit remainder",   "6502",    NULL,            s_div16           },
    { "div16_mega65",    "math",    "16/16 division (MEGA65 hardware)",           "45gs02",  "mega65_math",   s_div16_mega65    },
    { "bin_to_bcd",      "math",    "8-bit binary to 3-digit BCD",               "6502",    NULL,            s_bin_to_bcd      },
    { "bin_to_bcd_65c02","math",    "8-bit binary to 3-digit BCD (65C02 opt.)",  "65c02",   NULL,            s_bin_to_bcd_65c02},
    { "bcd_to_bin",      "math",    "2-digit BCD to 8-bit binary",               "6502",    NULL,            s_bcd_to_bin      },
    { "str_out",         "io",      "Print null-terminated string (C64 KERNAL)", "6502",    NULL,            s_str_out         },
    { "memcopy",         "memory",  "Copy N bytes (forward, non-overlapping)",   "6502",    NULL,            s_memcopy         },
    { "memfill",         "memory",  "Fill N bytes with a constant value",        "6502",    NULL,            s_memfill         },
    { "delay",           "time",    "Busy-wait delay via nested loops",          "6502",    NULL,            s_delay           },
    { "bitmap_init",          "bitmap",  "Init C64/MEGA65 hi-res 1bpp bitmap mode",   "6502",    "vic2",          s_bitmap_init          },
    { "bitmap_plot",          "bitmap",  "Set/clear/toggle pixel in 1bpp bitmap",     "6502",    "vic2",          s_bitmap_plot          },
    { "bitmap_setcell",       "bitmap",  "Set 8x8 cell fg/bg colour in screen RAM",   "6502",    "vic2",          s_bitmap_setcell       },
    { "bitmap_clear",         "bitmap",  "Clear 8000-byte 1bpp bitmap (software)",    "6502",    "vic2",          s_bitmap_clear         },
    { "bitmap_clear_mega65",  "bitmap",  "Clear 1bpp bitmap via MEGA65 DMA fill",     "45gs02",  "mega65_dma",    s_bitmap_clear_mega65  },
    { "dma_copy",        "dma",     "Copy N bytes via MEGA65 enhanced DMA",      "45gs02",  "mega65_dma",    s_dma_copy        },
    { "dma_fill",        "dma",     "Fill N bytes with a constant via DMA",      "45gs02",  "mega65_dma",    s_dma_fill        },
    { "dma_copy_far",    "dma",     "28-bit copy with MB option tokens",         "45gs02",  "mega65_dma",    s_dma_copy_far    },
    { "sprite_init",         "sprite",  "Full VIC-II sprite init (pos/enable/colour/ptr)", "6502",    "vic2",          s_sprite_init         },
    { "sprite_move",         "sprite",  "Update sprite X/Y position and X MSB",           "6502",    "vic2",          s_sprite_move         },
    { "sprite_setcolor",     "sprite",  "Set sprite foreground colour ($D027+N)",          "6502",    "vic2",          s_sprite_setcolor     },
    { "sprite_mc_init",      "sprite",  "Enable VIC-II multicolour mode for one sprite",  "6502",    "vic2",          s_sprite_mc_init      },
    { "sprite_data",         "sprite",  "64-byte diamond sprite shape at $2080",           "6502",    "vic2",          s_sprite_data         },
    { "sprite_mega65_16col", "sprite",  "Enable MEGA65 VIC-IV 16-colour (4bpp) for sprite","45gs02",  "vic2",          s_sprite_mega65_16col },
};

const int g_snippet_count = (int)(sizeof(g_snippets) / sizeof(g_snippets[0]));

const snippet_t *snippet_find(const char *name) {
    for (int i = 0; i < g_snippet_count; i++) {
        if (strcmp(g_snippets[i].name, name) == 0)
            return &g_snippets[i];
    }
    return NULL;
}
