#include "patterns.h"
#include <string.h>

/* =========================================================================
 * add16
 * ========================================================================= */
static const char s_add16[] =
"; add16 — 16-bit addition\n"
";\n"
"; Adds a 16-bit source value to a 16-bit destination, both in zero page.\n"
";\n"
"; PARAMS — change these equates to suit your layout:\n"
";   SRC_LO  = source  low  byte address\n"
";   SRC_HI  = source  high byte address  (SRC_LO + 1)\n"
";   DST_LO  = destination low  byte address\n"
";   DST_HI  = destination high byte address  (DST_LO + 1)\n"
";\n"
"; Result : [DST_HI:DST_LO] += [SRC_HI:SRC_LO]\n"
"; Clobbers: A, N, Z, C, V\n"
"; Cycles  : 14\n"
";\n"
"SRC_LO  = $10\n"
"SRC_HI  = $11\n"
"DST_LO  = $12\n"
"DST_HI  = $13\n"
"\n"
"add16:\n"
"    CLC\n"
"    LDA DST_LO\n"
"    ADC SRC_LO\n"
"    STA DST_LO\n"
"    LDA DST_HI\n"
"    ADC SRC_HI\n"
"    STA DST_HI\n"
"    RTS\n";

/* =========================================================================
 * sub16
 * ========================================================================= */
static const char s_sub16[] =
"; sub16 — 16-bit subtraction\n"
";\n"
"; Subtracts a 16-bit source from a 16-bit destination, both in zero page.\n"
";\n"
"; PARAMS:\n"
";   SRC_LO  = subtrahend low  byte address\n"
";   SRC_HI  = subtrahend high byte address\n"
";   DST_LO  = minuend / result low  byte address\n"
";   DST_HI  = minuend / result high byte address\n"
";\n"
"; Result : [DST_HI:DST_LO] -= [SRC_HI:SRC_LO]\n"
"; Clobbers: A, N, Z, C, V\n"
"; Cycles  : 14\n"
";\n"
"SRC_LO  = $10\n"
"SRC_HI  = $11\n"
"DST_LO  = $12\n"
"DST_HI  = $13\n"
"\n"
"sub16:\n"
"    SEC\n"
"    LDA DST_LO\n"
"    SBC SRC_LO\n"
"    STA DST_LO\n"
"    LDA DST_HI\n"
"    SBC SRC_HI\n"
"    STA DST_HI\n"
"    RTS\n";

/* =========================================================================
 * mul8  — software 8×8 = 16-bit (shift-and-add), all 6502 variants
 * ========================================================================= */
static const char s_mul8[] =
"; mul8 — unsigned 8x8 = 16-bit multiply (software, all 6502 variants)\n"
";\n"
"; Standard shift-and-add algorithm (8 iterations).\n"
";\n"
"; PARAMS:\n"
";   FACTOR_A  = $10   ; 8-bit multiplicand (preserved)\n"
";   FACTOR_B  = $11   ; 8-bit multiplier   (destroyed — shift register)\n"
";   RESULT_LO = $12   ; product low  byte  (out)\n"
";   RESULT_HI = $13   ; product high byte  (out)\n"
";   TMP_HI    = $14   ; high byte of shifted FACTOR_A (internal)\n"
";\n"
"; Result : [RESULT_HI:RESULT_LO] = FACTOR_A * FACTOR_B  (0..65025)\n"
"; Clobbers: A, X, FACTOR_B, TMP_HI, N, Z, C\n"
"; Cycles  : ~153 worst-case\n"
";\n"
"FACTOR_A  = $10\n"
"FACTOR_B  = $11\n"
"RESULT_LO = $12\n"
"RESULT_HI = $13\n"
"TMP_HI    = $14\n"
"\n"
"mul8:\n"
"    LDA #0\n"
"    STA RESULT_LO\n"
"    STA RESULT_HI\n"
"    STA TMP_HI\n"
"    LDX #8              ; 8 bit-iterations\n"
".mul8_loop:\n"
"    LSR FACTOR_B        ; shift multiplier right; bit 0 -> carry\n"
"    BCC .mul8_skip      ; bit was 0: skip add\n"
"    CLC\n"
"    LDA RESULT_LO\n"
"    ADC FACTOR_A\n"
"    STA RESULT_LO\n"
"    LDA RESULT_HI\n"
"    ADC TMP_HI\n"
"    STA RESULT_HI\n"
".mul8_skip:\n"
"    ASL FACTOR_A        ; shift multiplicand left (16-bit)\n"
"    ROL TMP_HI\n"
"    DEX\n"
"    BNE .mul8_loop\n"
"    RTS\n";

/* =========================================================================
 * mul8_mega65 — hardware 8×8 multiply using MEGA65 math coprocessor
 * ========================================================================= */
static const char s_mul8_mega65[] =
"; mul8_mega65 — 8x8 = 16-bit multiply using MEGA65 hardware math unit\n"
";\n"
"; The MEGA65 math coprocessor produces the result combinatorially;\n"
"; the product is valid as soon as FACTOR_B is written to MATH_MUL_B_LO.\n"
"; Write 0 to the high-byte registers to keep this a true 8x8 operation\n"
"; (the hardware supports up to 16x16 = 32-bit).\n"
";\n"
"; PARAMS:\n"
";   FACTOR_A  = $10   ; 8-bit multiplicand\n"
";   FACTOR_B  = $11   ; 8-bit multiplier\n"
";   RESULT_LO = $12   ; product low  byte (out)\n"
";   RESULT_HI = $13   ; product high byte (out)\n"
";\n"
"; Result : [RESULT_HI:RESULT_LO] = FACTOR_A * FACTOR_B  (0..65025)\n"
"; Clobbers: A, N, Z\n"
"; Cycles  : ~16 (vs ~153 software)\n"
";\n"
"FACTOR_A     = $10\n"
"FACTOR_B     = $11\n"
"RESULT_LO    = $12\n"
"RESULT_HI    = $13\n"
"\n"
"MATH_MUL_A_LO = $D770   ; multiplicand A low byte\n"
"MATH_MUL_A_HI = $D771   ; multiplicand A high byte (clear for 8-bit)\n"
"MATH_MUL_B_LO = $D772   ; multiplicand B low byte\n"
"MATH_MUL_B_HI = $D773   ; multiplicand B high byte (clear for 8-bit)\n"
"MATH_RESULT_0 = $D778   ; result byte 0 (LSB)\n"
"MATH_RESULT_1 = $D779   ; result byte 1\n"
"\n"
"mul8_mega65:\n"
"    LDA #0\n"
"    STA MATH_MUL_A_HI   ; keep this an 8-bit operand\n"
"    STA MATH_MUL_B_HI\n"
"    LDA FACTOR_A\n"
"    STA MATH_MUL_A_LO   ; write A first\n"
"    LDA FACTOR_B\n"
"    STA MATH_MUL_B_LO   ; write B; result is immediately ready\n"
"    LDA MATH_RESULT_0\n"
"    STA RESULT_LO\n"
"    LDA MATH_RESULT_1\n"
"    STA RESULT_HI\n"
"    RTS\n";

/* =========================================================================
 * div16 — software 16÷8 = 16-bit quotient + 8-bit remainder
 * ========================================================================= */
static const char s_div16[] =
"; div16 — unsigned 16÷8 division (software, all 6502 variants)\n"
";\n"
"; Classic restoring long-division.  The 16-bit dividend is consumed\n"
"; in-place and replaced by the 16-bit quotient on exit.\n"
";\n"
"; PARAMS:\n"
";   DIVIDEND_LO = $10   ; dividend low  byte (in); quotient low  byte (out)\n"
";   DIVIDEND_HI = $11   ; dividend high byte (in); quotient high byte (out)\n"
";   DIVISOR     = $12   ; 8-bit divisor (must be non-zero)\n"
";   REMAINDER   = $13   ; 8-bit remainder (out)\n"
";\n"
"; Clobbers: A, X, N, Z, C\n"
"; Cycles  : ~320 worst-case\n"
"; Note    : quotient is 16-bit; overflow not detected.\n"
";\n"
"DIVIDEND_LO = $10\n"
"DIVIDEND_HI = $11\n"
"DIVISOR     = $12\n"
"REMAINDER   = $13\n"
"\n"
"div16:\n"
"    LDA #0\n"
"    STA REMAINDER\n"
"    LDX #16             ; 16 bit-iterations\n"
".div16_loop:\n"
"    ASL DIVIDEND_LO     ; shift dividend/quotient left (carry <- bit 15)\n"
"    ROL DIVIDEND_HI\n"
"    ROL REMAINDER       ; shift carry into remainder\n"
"    SEC\n"
"    LDA REMAINDER\n"
"    SBC DIVISOR\n"
"    BCC .div16_no_sub   ; remainder < divisor: restore\n"
"    STA REMAINDER       ; keep subtracted remainder\n"
"    INC DIVIDEND_LO     ; set quotient bit (bit 0 was just shifted in as 0)\n"
".div16_no_sub:\n"
"    DEX\n"
"    BNE .div16_loop\n"
"    RTS\n";

/* =========================================================================
 * div16_mega65 — hardware 16÷16 using MEGA65 math coprocessor
 * ========================================================================= */
static const char s_div16_mega65[] =
"; div16_mega65 — 16÷16 division using MEGA65 hardware math unit\n"
";\n"
"; The MEGA65 math coprocessor computes the result combinatorially;\n"
"; quotient and remainder are available immediately after writing the\n"
"; divisor high byte.\n"
";\n"
"; PARAMS:\n"
";   DIVIDEND_LO = $10   ; dividend low  byte\n"
";   DIVIDEND_HI = $11   ; dividend high byte\n"
";   DIVISOR_LO  = $12   ; divisor  low  byte\n"
";   DIVISOR_HI  = $13   ; divisor  high byte (0 for 16÷8)\n"
";   RESULT_LO   = $14   ; quotient  low  byte (out)\n"
";   RESULT_HI   = $15   ; quotient  high byte (out)\n"
";   REMAINDER   = $16   ; remainder low  byte (out)\n"
";\n"
"; Clobbers: A, N, Z\n"
"; Cycles  : ~20 (vs ~320 software)\n"
";\n"
"DIVIDEND_LO   = $10\n"
"DIVIDEND_HI   = $11\n"
"DIVISOR_LO    = $12\n"
"DIVISOR_HI    = $13\n"
"RESULT_LO     = $14\n"
"RESULT_HI     = $15\n"
"REMAINDER     = $16\n"
"\n"
"MATH_DIV_A_LO = $D768   ; dividend low  byte\n"
"MATH_DIV_A_HI = $D769   ; dividend high byte\n"
"MATH_DIV_B_LO = $D76A   ; divisor  low  byte\n"
"MATH_DIV_B_HI = $D76B   ; divisor  high byte\n"
"MATH_RESULT_0 = $D778   ; result byte 0 — quotient LSB\n"
"MATH_RESULT_1 = $D779   ; result byte 1 — quotient MSB\n"
"MATH_RESULT_2 = $D77A   ; result byte 2 — remainder LSB\n"
"\n"
"div16_mega65:\n"
"    LDA DIVIDEND_LO\n"
"    STA MATH_DIV_A_LO\n"
"    LDA DIVIDEND_HI\n"
"    STA MATH_DIV_A_HI\n"
"    LDA DIVISOR_LO\n"
"    STA MATH_DIV_B_LO\n"
"    LDA DIVISOR_HI\n"
"    STA MATH_DIV_B_HI   ; write completes; result ready immediately\n"
"    LDA MATH_RESULT_0\n"
"    STA RESULT_LO\n"
"    LDA MATH_RESULT_1\n"
"    STA RESULT_HI\n"
"    LDA MATH_RESULT_2\n"
"    STA REMAINDER\n"
"    RTS\n";

/* =========================================================================
 * bin_to_bcd — 8-bit binary to 3-digit BCD (subtraction loop, all 6502)
 * ========================================================================= */
static const char s_bin_to_bcd[] =
"; bin_to_bcd — convert 8-bit binary (0..255) to 3 decimal digits\n"
";\n"
"; Iterative subtraction: peel off hundreds, then tens, remainder = units.\n"
";\n"
"; PARAMS:\n"
";   INPUT    = $10   ; 8-bit binary input (preserved)\n"
";   HUNDREDS = $11   ; hundreds digit (0..2) out\n"
";   TENS     = $12   ; tens     digit (0..9) out\n"
";   UNITS    = $13   ; units    digit (0..9) out\n"
";\n"
"; Clobbers: A, X, Y, N, Z, C\n"
"; Cycles  : ~90 worst-case (value=255)\n"
";\n"
"INPUT    = $10\n"
"HUNDREDS = $11\n"
"TENS     = $12\n"
"UNITS    = $13\n"
"\n"
"bin_to_bcd:\n"
"    LDX #0\n"
"    LDY #0\n"
"    LDA INPUT\n"
".bcd_100s:\n"
"    CMP #100\n"
"    BCC .bcd_10s\n"
"    SBC #100            ; C set from CMP, so SBC = subtract without borrow\n"
"    INX\n"
"    JMP .bcd_100s\n"
".bcd_10s:\n"
"    CMP #10\n"
"    BCC .bcd_done\n"
"    SBC #10\n"
"    INY\n"
"    JMP .bcd_10s\n"
".bcd_done:\n"
"    STA UNITS\n"
"    STX HUNDREDS\n"
"    STY TENS\n"
"    RTS\n";

/* =========================================================================
 * bin_to_bcd_65c02 — 65C02 optimised: STZ, BRA, reliable decimal flags
 * ========================================================================= */
static const char s_bin_to_bcd_65c02[] =
"; bin_to_bcd_65c02 — 8-bit binary to 3-digit BCD (65C02 optimised)\n"
";\n"
"; Same subtraction algorithm as the 6502 version but uses 65C02\n"
"; instructions: STZ to zero registers and BRA for short branches.\n"
"; On 65C02 the N, Z, V flags are valid after decimal-mode ADC/SBC,\n"
"; which is exploited here to skip an explicit CMP.\n"
";\n"
"; PARAMS:\n"
";   INPUT    = $10   ; 8-bit binary input\n"
";   HUNDREDS = $11   ; hundreds digit (0..2) out\n"
";   TENS     = $12   ; tens     digit (0..9) out\n"
";   UNITS    = $13   ; units    digit (0..9) out\n"
";\n"
"; Clobbers: A, X, Y, N, Z, C\n"
";\n"
"INPUT    = $10\n"
"HUNDREDS = $11\n"
"TENS     = $12\n"
"UNITS    = $13\n"
"\n"
"bin_to_bcd_65c02:\n"
"    LDX #0\n"
"    LDY #0\n"
"    LDA INPUT\n"
".bcd_100s:\n"
"    CMP #100\n"
"    BCC .bcd_10s        ; BCC instead of JMP-to-skip (65C02: BRA available too)\n"
"    SBC #100\n"
"    INX\n"
"    BRA .bcd_100s       ; 65C02 branch-always (2-byte, no JMP needed)\n"
".bcd_10s:\n"
"    CMP #10\n"
"    BCC .bcd_done\n"
"    SBC #10\n"
"    INY\n"
"    BRA .bcd_10s\n"
".bcd_done:\n"
"    STA UNITS\n"
"    STX HUNDREDS\n"
"    STY TENS\n"
"    RTS\n";

/* =========================================================================
 * bcd_to_bin — 2-digit packed BCD to 8-bit binary
 * ========================================================================= */
static const char s_bcd_to_bin[] =
"; bcd_to_bin — convert 2 BCD digits to 8-bit binary\n"
";\n"
"; Computes: RESULT = TENS*10 + UNITS\n"
"; Uses the identity: tens*10 = tens*8 + tens*2\n"
";                            = (tens << 3) + (tens << 1)\n"
";\n"
"; PARAMS:\n"
";   TENS   = $10   ; tens   digit (0..9)\n"
";   UNITS  = $11   ; units  digit (0..9)\n"
";   RESULT = $12   ; binary result (out, 0..99)\n"
";\n"
"; Clobbers: A, N, Z, C\n"
"; Cycles  : 18\n"
";\n"
"TENS   = $10\n"
"UNITS  = $11\n"
"RESULT = $12\n"
"\n"
"bcd_to_bin:\n"
"    LDA TENS\n"
"    ASL             ; A = TENS * 2\n"
"    STA RESULT      ; save TENS * 2\n"
"    ASL             ; A = TENS * 4\n"
"    ASL             ; A = TENS * 8\n"
"    CLC\n"
"    ADC RESULT      ; A = TENS*8 + TENS*2 = TENS*10\n"
"    ADC UNITS       ; A = TENS*10 + UNITS\n"
"    STA RESULT\n"
"    RTS\n";

/* =========================================================================
 * str_out — print null-terminated string via C64 KERNAL CHROUT
 * ========================================================================= */
static const char s_str_out[] =
"; str_out — print a null-terminated PETSCII string via C64 KERNAL\n"
";\n"
"; Calls CHROUT ($FFD2) for each byte until a $00 terminator is found.\n"
"; Y register advances as index; safe for strings up to 255 bytes.\n"
"; For other platforms, replace CHROUT with your character output routine.\n"
";\n"
"; PARAMS:\n"
";   STR_LO = $10   ; low  byte of string address\n"
";   STR_HI = $11   ; high byte of string address\n"
";\n"
"; Clobbers: A, Y, N, Z\n"
"; Cycles  : 14 + 20*len  (approx, with KERNAL overhead excluded)\n"
";\n"
"STR_LO = $10\n"
"STR_HI = $11\n"
"CHROUT = $FFD2      ; C64 KERNAL — replace for other platforms\n"
"\n"
"str_out:\n"
"    LDY #0\n"
".str_loop:\n"
"    LDA (STR_LO),Y\n"
"    BEQ .str_done       ; null terminator\n"
"    JSR CHROUT\n"
"    INY\n"
"    BNE .str_loop       ; stop if Y wraps (string > 255 chars)\n"
".str_done:\n"
"    RTS\n";

/* =========================================================================
 * memcopy — copy N bytes (up to 255) from source to destination
 * ========================================================================= */
static const char s_memcopy[] =
"; memcopy — copy N bytes (1..255) from source to destination\n"
";\n"
"; Simple forward copy using indirect indexed addressing.\n"
"; Does NOT handle overlapping regions; use memmove for that.\n"
";\n"
"; PARAMS:\n"
";   SRC_LO = $10   ; source address low  byte\n"
";   SRC_HI = $11   ; source address high byte\n"
";   DST_LO = $12   ; destination address low  byte\n"
";   DST_HI = $13   ; destination address high byte\n"
";   COUNT  = $14   ; number of bytes (1..255; 0 = no-op)\n"
";\n"
"; Clobbers: A, X, Y, N, Z\n"
"; Cycles  : 5 + 15*COUNT  (approx)\n"
";\n"
"SRC_LO = $10\n"
"SRC_HI = $11\n"
"DST_LO = $12\n"
"DST_HI = $13\n"
"COUNT  = $14\n"
"\n"
"memcopy:\n"
"    LDA COUNT\n"
"    BEQ .mc_done\n"
"    TAX             ; X = byte count\n"
"    LDY #0\n"
".mc_loop:\n"
"    LDA (SRC_LO),Y\n"
"    STA (DST_LO),Y\n"
"    INY\n"
"    DEX\n"
"    BNE .mc_loop\n"
".mc_done:\n"
"    RTS\n";

/* =========================================================================
 * memfill — fill N bytes with a constant value
 * ========================================================================= */
static const char s_memfill[] =
"; memfill — fill N bytes (1..255) with a constant value\n"
";\n"
"; PARAMS:\n"
";   DST_LO = $10   ; destination address low  byte\n"
";   DST_HI = $11   ; destination address high byte\n"
";   VALUE  = $12   ; byte value to write\n"
";   COUNT  = $13   ; number of bytes (1..255; 0 = no-op)\n"
";\n"
"; Clobbers: A, X, Y, N, Z\n"
"; Cycles  : 5 + 13*COUNT  (approx)\n"
";\n"
"DST_LO = $10\n"
"DST_HI = $11\n"
"VALUE  = $12\n"
"COUNT  = $13\n"
"\n"
"memfill:\n"
"    LDA COUNT\n"
"    BEQ .mf_done\n"
"    TAX             ; X = byte count\n"
"    LDA VALUE\n"
"    LDY #0\n"
".mf_loop:\n"
"    STA (DST_LO),Y\n"
"    INY\n"
"    DEX\n"
"    BNE .mf_loop\n"
".mf_done:\n"
"    RTS\n";

/* =========================================================================
 * delay — busy-wait delay using two nested countdown loops
 * ========================================================================= */
static const char s_delay[] =
"; delay — busy-wait delay via nested countdown loops\n"
";\n"
"; Cycle formula: (OUTER * INNER * 5) + OUTER * 9 + overhead\n"
";\n"
"; Worked example (PAL C64, ~985 kHz):\n"
";   1 frame @ 50 Hz = ~19656 cycles\n"
";   OUTER=100, INNER=39 -> 100*(39*5+9)+ovhd = 100*204 = ~20400 cycles\n"
";   Tune INNER/OUTER to taste with a cycle counter.\n"
";\n"
"; For delays longer than ~130000 cycles, call multiple times or add a\n"
"; third outer loop using a zero-page counter.\n"
";\n"
"; PARAMS:\n"
";   OUTER = $10   ; outer loop count (1..255)\n"
";   INNER = $11   ; inner loop count (1..255)\n"
";\n"
"; Clobbers: X, Y, N, Z\n"
";\n"
"OUTER = $10\n"
"INNER = $11\n"
"\n"
"delay:\n"
"    LDY OUTER           ; 3c\n"
".delay_outer:\n"
"    LDX INNER           ; 3c  per outer pass\n"
".delay_inner:\n"
"    DEX                 ; 2c\n"
"    BNE .delay_inner    ; 3c taken / 2c not taken  => ~5c per inner iter\n"
"    DEY                 ; 2c\n"
"    BNE .delay_outer    ; 3c / 2c                  => ~9c outer overhead\n"
"    RTS\n";

/* =========================================================================
 * Snippet table
 * ========================================================================= */
const snippet_t g_snippets[] = {
    /* name              category   summary                                       processor  body */
    { "add16",           "math",    "16-bit addition (zero-page)",                "6502",    s_add16           },
    { "sub16",           "math",    "16-bit subtraction (zero-page)",             "6502",    s_sub16           },
    { "mul8",            "math",    "8x8 = 16-bit multiply (software)",           "6502",    s_mul8            },
    { "mul8_mega65",     "math",    "8x8 = 16-bit multiply (MEGA65 hardware)",    "45gs02",  s_mul8_mega65     },
    { "div16",           "math",    "16/8 = 16-bit quotient + 8-bit remainder",   "6502",    s_div16           },
    { "div16_mega65",    "math",    "16/16 division (MEGA65 hardware)",           "45gs02",  s_div16_mega65    },
    { "bin_to_bcd",      "math",    "8-bit binary to 3-digit BCD",               "6502",    s_bin_to_bcd      },
    { "bin_to_bcd_65c02","math",    "8-bit binary to 3-digit BCD (65C02 opt.)",  "65c02",   s_bin_to_bcd_65c02},
    { "bcd_to_bin",      "math",    "2-digit BCD to 8-bit binary",               "6502",    s_bcd_to_bin      },
    { "str_out",         "io",      "Print null-terminated string (C64 KERNAL)", "6502",    s_str_out         },
    { "memcopy",         "memory",  "Copy N bytes (forward, non-overlapping)",   "6502",    s_memcopy         },
    { "memfill",         "memory",  "Fill N bytes with a constant value",        "6502",    s_memfill         },
    { "delay",           "time",    "Busy-wait delay via nested loops",          "6502",    s_delay           },
};

const int g_snippet_count = (int)(sizeof(g_snippets) / sizeof(g_snippets[0]));

const snippet_t *snippet_find(const char *name) {
    for (int i = 0; i < g_snippet_count; i++) {
        if (strcmp(g_snippets[i].name, name) == 0)
            return &g_snippets[i];
    }
    return NULL;
}
