 // Test all instructions for 6502

 // Generated by generate_opcode_tests.py

    .cpu _65c02
    * = $1000

    lda #$12
    lda $1234
    lda $1234,x
    lda $1234,y
    lda $12
    lda $12,x
    lda ($12,x)
    lda ($12),y
    ldx #$12
    ldx $1234
    ldx $1234,y
    ldx $12
    ldx $12,y
    ldy #$12
    ldy $1234
    ldy $1234,x
    ldy $12
    ldy $12,x
    sta $1234
    sta $1234,x
    sta $1234,y
    sta $12
    sta $12,x
    sta ($12,x)
    sta ($12),y
    stx $1234
    stx $12
    stx $12,y
    sty $1234
    sty $12
    sty $12,x
    adc #$12
    adc $1234
    adc $1234,x
    adc $1234,y
    adc $12
    adc $12,x
    adc ($12,x)
    adc ($12),y
    sbc #$12
    sbc $1234
    sbc $12
    sbc $12,x
    sbc $1234,x
    sbc $1234,y
    sbc ($12,x)
    sbc ($12),y
    cmp #$12
    cmp $1234
    cmp $12
    cmp $12,x
    cmp $1234,x
    cmp $1234,y
    cmp ($12,x)
    cmp ($12),y
    cpx #$12
    cpx $12
    cpx $1234
    cpy #$12
    cpy $12
    cpy $1234
    inc $1234
    inc $12
    inc $12,x
    inc $1234,x
    inc
    inx
    iny
    dec $1234
    dec $12
    dec $12,x
    dec $1234,x
    dec
    dex
    dey
    asl $1234
    asl $12
    asl $12,x
    asl $1234,x
    asl
    lsr $1234
    lsr $12
    lsr $12,x
    lsr $1234,x
    lsr
    rol $1234
    rol $12
    rol $12,x
    rol $1234,x
    rol
    ror $1234
    ror $12
    ror $12,x
    ror $1234,x
    ror
    and #$12
    and $1234
    and $12
    and $12,x
    and $1234,x
    and $1234,y
    and ($12,x)
    and ($12),y
    eor #$12
    eor $1234
    eor $12
    eor $12,x
    eor $1234,x
    eor $1234,y
    eor ($12,x)
    eor ($12),y
    ora #$12
    ora $1234
    ora $12
    ora $12,x
    ora $1234,x
    ora $1234,y
    ora ($12,x)
    ora ($12),y
    bit $12
    bit $1234
    jmp $1234
    jmp ($1234)
    jsr $1234
    rts
    bra *+3
    bcc *+3
    bcs *+3
    beq *+3
    bne *+3
    bmi *+3
    bpl *+3
    bvs *+3
    bvc *+3
    clc
    sec
    cld
    sed
    cli
    sei
    clv
    tax
    txa
    tay
    tya
    tsx
    txs
    pha
    pla
    php
    plp
    nop
    nop
    nop

    rts

