 // Test all instructions for 45gs02

 // Generated by generate_opcode_tests.py

    .cpu _45gs02
    * = $1000

    lda #$12
    lda $1234
    lda $1234,x
    lda $1234,y
    lda $12
    lda $12,x
    asw $1234
    row $1234
    dew $12
    inw $12
    phw #$1234
    phw $1234
    phz
    plz
    ldz $1234,x
    tsy
    tys
    taz
    tza
    cle
    see
    neg
    tab
    tba
    rtn #$12
    lbra *+4
    lbsr *+4
    asr
    asr $12
    asr $12,x
    map
    lda ($12,x)
    lda ($12),y
    ldz #$12
    ldz $1234
    ldx #$12
    ldx $1234
    ldx $1234,y
    ldx $12
    ldx $12,y
    ldy #$12
    ldy $1234
    ldy $1234,x
    ldy $12
    ldy $12,x
    sta $1234
    sta $1234,x
    sta $1234,y
    sta $12
    sta $12,x
    sta ($12,x)
    sta ($12),y
    stz $1234
    stz $12
    stx $1234
    stx $12
    stx $12,y
    stx $1234,y
    sty $1234
    sty $12
    sty $12,x
    sty $1234,x
    adc #$12
    adc $1234
    adc $1234,x
    adc $1234,y
    adc $12
    adc $12,x
    adc ($12,x)
    adc ($12),y
    sbc #$12
    sbc $1234
    sbc $12
    sbc $12,x
    sbc ($12,x)
    sbc ($12),y
    sbc $1234,y
    sbc $1234,x
    lda (($12)),z
    sta (($12)),z
    adc (($12)),z
    sbc (($12)),z
    cmp (($12)),z
    ora (($12)),z
    and (($12)),z
    eor (($12)),z
    lda (($12)),z
    sta (($12)),z
    adc (($12)),z
    sbc (($12)),z
    cmp (($12)),z
    ora (($12)),z
    and (($12)),z
    eor (($12)),z
    cmp #$12
    cmp $1234
    cmp $12
    cmp $12,x
    cmp ($12,x)
    cmp ($12),y
    cmp $1234,y
    cmp $1234,x
    cpz #$12
    cpz $1234
    cpz $12
    cpx #$12
    cpx $12
    cpx $1234
    cpy #$12
    cpy $12
    cpy $1234
    inc
    inx
    iny
    inz
    dec $1234
    dec $12
    dec $12,x
    dec $1234,x
    dec
    dex
    dey
    dez
    asl $1234
    asl
    asl $12
    asl $12,x
    asl $1234,x
    lsr $1234
    lsr
    lsr $12
    lsr $12,x
    lsr $1234,x
    rol $1234
    rol
    rol $12
    rol $12,x
    rol $1234,x
    ror $1234
    ror
    ror $12
    ror $12,x
    ror $1234,x
    and #$12
    and $1234
    and $12
    and $12,x
    and ($12,x)
    and ($12),y
    and $1234,y
    and $1234,x
    eor #$12
    eor $1234
    eor $12
    eor $12,x
    eor ($12,x)
    eor ($12),y
    eor $1234,y
    eor $1234,x
    ora #$12
    ora $1234
    ora $12
    ora $12,x
    ora ($12,x)
    ora ($12),y
    ora $1234,y
    ora $1234,x
    bit $12
    bit $1234
    bit #$12
    bit $12,x
    bit $1234,x
    trb $12
    trb $1234
    tsb $12
    tsb $1234
    rmb0 $12
    rmb1 $12
    rmb2 $12
    rmb3 $12
    rmb4 $12
    rmb5 $12
    rmb6 $12
    rmb7 $12
    smb0 $12
    smb1 $12
    smb2 $12
    smb3 $12
    smb4 $12
    smb5 $12
    smb6 $12
    smb7 $12
    bbr0 $12, *+3
    bbr1 $12, *+3
    bbr2 $12, *+3
    bbr3 $12, *+3
    bbr4 $12, *+3
    bbr5 $12, *+3
    bbr6 $12, *+3
    bbr7 $12, *+3
    bbs0 $12, *+3
    bbs1 $12, *+3
    bbs2 $12, *+3
    bbs3 $12, *+3
    bbs4 $12, *+3
    bbs5 $12, *+3
    bbs6 $12, *+3
    bbs7 $12, *+3
    stz $1234
    stz $1234,x
    stz $12
    stz $12,x
    bra *+3
    bra *+4
    lbra *+4
    lbra *+4
    jmp $1234
    jmp ($1234)
    jmp ($12,x)
    jsr $1234
    jsr ($1234)
    jsr ($1234,x)
    rts
    bcc *+3
    lbcc *+4
    lbcc *+4
    bcs *+3
    lbcs *+4
    lbcs *+4
    beq *+3
    lbeq *+4
    lbeq *+4
    bne *+3
    lbne *+4
    lbne *+4
    bmi *+3
    lbmi *+4
    lbmi *+4
    bpl *+3
    lbpl *+4
    lbpl *+4
    bvs *+3
    lbvs *+4
    lbvs *+4
    bvc *+3
    lbvc *+4
    lbvc *+4
    clc
    sec
    cld
    sed
    cli
    sei
    clv
    tax
    txa
    tay
    tya
    tsx
    txs
    pha
    pla
    phx
    plx
    phy
    ply
    php
    plp
    nop
    nop
    eom
    ldq $12
    ldq $1234
    ldq ($12),z
    stq (($12))
    ldq ($12),z
    stq ($12)
    ldq $12
    stq (($12))
    adcq $12
    adcq $1234
    sbcq $12
    sbcq $1234
    cpq $12
    cpq $1234
    eorq $12
    eorq $1234
    andq $12
    andq $1234
    bitq $12
    bitq $1234
    orq $12
    orq $1234
    aslq
    aslq $12
    aslq $12,x
    aslq $1234
    aslq $1234,x
    asrq
    asrq $12
    asrq $12,x
    lsrq
    lsrq $12
    lsrq $12,x
    lsrq $1234
    lsrq $1234,x
    rolq
    rolq $12
    rolq $12,x
    rolq $1234
    rolq $1234,x
    rorq
    rorq $12
    rorq $12,x
    rorq $1234
    rorq $1234,x
    inq
    inq $12
    inq $12,x
    inq $1234
    inq $1234,x
    deq
    deq $12
    deq $12,x
    deq $1234
    deq $1234,x
    adcq ($12)
    adcq ($12)
    sbcq ($12)
    sbcq ($12)
    cpq ($12)
    cpq ($12)
    andq ($12)
    andq ($12)
    eorq ($12)
    eorq ($12)
    orq ($12)
    orq ($12)

    rts

